/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class DataLogger extends CallbackManagerXda {
  private transient long swigCPtr;

  protected DataLogger(long cPtr, boolean cMemoryOwn) {
    super(minimalJNI.DataLogger_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(DataLogger obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_DataLogger(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public boolean writeMessage(XsMessageClass message) {
    return minimalJNI.DataLogger_writeMessage(swigCPtr, this, XsMessageClass.getCPtr(message), message);
  }

  public void close() {
    minimalJNI.DataLogger_close(swigCPtr, this);
  }

}
