/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class SnapshotType {
  public final static SnapshotType ST_Awinda = new SnapshotType("ST_Awinda", minimalJNI.ST_Awinda_get());
  public final static SnapshotType ST_Full = new SnapshotType("ST_Full");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SnapshotType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SnapshotType.class + " with value " + swigValue);
  }

  private SnapshotType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SnapshotType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SnapshotType(String swigName, SnapshotType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SnapshotType[] swigValues = { ST_Awinda, ST_Full };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

