/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsAccessControlMode {
  public final static XsAccessControlMode XACM_None = new XsAccessControlMode("XACM_None", minimalJNI.XACM_None_get());
  public final static XsAccessControlMode XACM_BlackList = new XsAccessControlMode("XACM_BlackList", minimalJNI.XACM_BlackList_get());
  public final static XsAccessControlMode XACM_WhiteList = new XsAccessControlMode("XACM_WhiteList", minimalJNI.XACM_WhiteList_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsAccessControlMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsAccessControlMode.class + " with value " + swigValue);
  }

  private XsAccessControlMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsAccessControlMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsAccessControlMode(String swigName, XsAccessControlMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsAccessControlMode[] swigValues = { XACM_None, XACM_BlackList, XACM_WhiteList };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

