/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsAlignmentFrame {
  public final static XsAlignmentFrame XAF_Sensor = new XsAlignmentFrame("XAF_Sensor");
  public final static XsAlignmentFrame XAF_Local = new XsAlignmentFrame("XAF_Local");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsAlignmentFrame swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsAlignmentFrame.class + " with value " + swigValue);
  }

  private XsAlignmentFrame(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsAlignmentFrame(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsAlignmentFrame(String swigName, XsAlignmentFrame swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsAlignmentFrame[] swigValues = { XAF_Sensor, XAF_Local };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

