/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsCalibratedData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsCalibratedData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsCalibratedData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsCalibratedData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_acc(XsVector3 value) {
    minimalJNI.XsCalibratedData_m_acc_set(swigCPtr, this, XsVector3.getCPtr(value), value);
  }

  public XsVector3 getM_acc() {
    long cPtr = minimalJNI.XsCalibratedData_m_acc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsVector3(cPtr, false);
  }

  public void setM_gyr(XsVector3 value) {
    minimalJNI.XsCalibratedData_m_gyr_set(swigCPtr, this, XsVector3.getCPtr(value), value);
  }

  public XsVector3 getM_gyr() {
    long cPtr = minimalJNI.XsCalibratedData_m_gyr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsVector3(cPtr, false);
  }

  public void setM_mag(XsVector3 value) {
    minimalJNI.XsCalibratedData_m_mag_set(swigCPtr, this, XsVector3.getCPtr(value), value);
  }

  public XsVector3 getM_mag() {
    long cPtr = minimalJNI.XsCalibratedData_m_mag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsVector3(cPtr, false);
  }

  public XsCalibratedData() {
    this(minimalJNI.new_XsCalibratedData__SWIG_0(), true);
  }

  public XsCalibratedData(XsCalibratedData other) {
    this(minimalJNI.new_XsCalibratedData__SWIG_1(XsCalibratedData.getCPtr(other), other), true);
  }

  public XsCalibratedData opSet(XsCalibratedData other) {
    return new XsCalibratedData(minimalJNI.XsCalibratedData_opSet(swigCPtr, this, XsCalibratedData.getCPtr(other), other), false);
  }

}
