/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsCanFrameFormat {
  public final static XsCanFrameFormat XCFF_11Bit_Identifier = new XsCanFrameFormat("XCFF_11Bit_Identifier", minimalJNI.XCFF_11Bit_Identifier_get());
  public final static XsCanFrameFormat XCFF_29Bit_Identifier = new XsCanFrameFormat("XCFF_29Bit_Identifier", minimalJNI.XCFF_29Bit_Identifier_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsCanFrameFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsCanFrameFormat.class + " with value " + swigValue);
  }

  private XsCanFrameFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsCanFrameFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsCanFrameFormat(String swigName, XsCanFrameFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsCanFrameFormat[] swigValues = { XCFF_11Bit_Identifier, XCFF_29Bit_Identifier };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

