/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsCanOutputConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsCanOutputConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsCanOutputConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsCanOutputConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_frameFormat(XsCanFrameFormat value) {
    minimalJNI.XsCanOutputConfiguration_m_frameFormat_set(swigCPtr, this, value.swigValue());
  }

  public XsCanFrameFormat getM_frameFormat() {
    return XsCanFrameFormat.swigToEnum(minimalJNI.XsCanOutputConfiguration_m_frameFormat_get(swigCPtr, this));
  }

  public void setM_dataIdentifier(XsCanDataIdentifier value) {
    minimalJNI.XsCanOutputConfiguration_m_dataIdentifier_set(swigCPtr, this, value.swigValue());
  }

  public XsCanDataIdentifier getM_dataIdentifier() {
    return XsCanDataIdentifier.swigToEnum(minimalJNI.XsCanOutputConfiguration_m_dataIdentifier_get(swigCPtr, this));
  }

  public void setM_id(long value) {
    minimalJNI.XsCanOutputConfiguration_m_id_set(swigCPtr, this, value);
  }

  public long getM_id() {
    return minimalJNI.XsCanOutputConfiguration_m_id_get(swigCPtr, this);
  }

  public void setM_frequency(int value) {
    minimalJNI.XsCanOutputConfiguration_m_frequency_set(swigCPtr, this, value);
  }

  public int getM_frequency() {
    return minimalJNI.XsCanOutputConfiguration_m_frequency_get(swigCPtr, this);
  }

  public XsCanOutputConfiguration() {
    this(minimalJNI.new_XsCanOutputConfiguration__SWIG_0(), true);
  }

  public XsCanOutputConfiguration(XsCanFrameFormat il, XsCanDataIdentifier di, long id, int freq) {
    this(minimalJNI.new_XsCanOutputConfiguration__SWIG_1(il.swigValue(), di.swigValue(), id, freq), true);
  }

  public boolean opEquals(XsCanOutputConfiguration other) {
    return minimalJNI.XsCanOutputConfiguration_opEquals(swigCPtr, this, XsCanOutputConfiguration.getCPtr(other), other);
  }

  public boolean opUnequals(XsCanOutputConfiguration other) {
    return minimalJNI.XsCanOutputConfiguration_opUnequals(swigCPtr, this, XsCanOutputConfiguration.getCPtr(other), other);
  }

}
