/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsConnectivityState {
  public final static XsConnectivityState XCS_Disconnected = new XsConnectivityState("XCS_Disconnected");
  public final static XsConnectivityState XCS_Rejected = new XsConnectivityState("XCS_Rejected");
  public final static XsConnectivityState XCS_PluggedIn = new XsConnectivityState("XCS_PluggedIn");
  public final static XsConnectivityState XCS_Wireless = new XsConnectivityState("XCS_Wireless");
  public final static XsConnectivityState XCS_WirelessOutOfRange = new XsConnectivityState("XCS_WirelessOutOfRange");
  public final static XsConnectivityState XCS_File = new XsConnectivityState("XCS_File");
  public final static XsConnectivityState XCS_Unknown = new XsConnectivityState("XCS_Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsConnectivityState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsConnectivityState.class + " with value " + swigValue);
  }

  private XsConnectivityState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsConnectivityState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsConnectivityState(String swigName, XsConnectivityState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsConnectivityState[] swigValues = { XCS_Disconnected, XCS_Rejected, XCS_PluggedIn, XCS_Wireless, XCS_WirelessOutOfRange, XCS_File, XCS_Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

