/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsDeviceState {
  public final static XsDeviceState XDS_Initial = new XsDeviceState("XDS_Initial");
  public final static XsDeviceState XDS_Config = new XsDeviceState("XDS_Config");
  public final static XsDeviceState XDS_Measurement = new XsDeviceState("XDS_Measurement");
  public final static XsDeviceState XDS_WaitingForRecordingStart = new XsDeviceState("XDS_WaitingForRecordingStart");
  public final static XsDeviceState XDS_Recording = new XsDeviceState("XDS_Recording");
  public final static XsDeviceState XDS_FlushingData = new XsDeviceState("XDS_FlushingData");
  public final static XsDeviceState XDS_Destructing = new XsDeviceState("XDS_Destructing");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDeviceState swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDeviceState.class + " with value " + swigValue);
  }

  private XsDeviceState(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDeviceState(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDeviceState(String swigName, XsDeviceState swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDeviceState[] swigValues = { XDS_Initial, XDS_Config, XDS_Measurement, XDS_WaitingForRecordingStart, XDS_Recording, XDS_FlushingData, XDS_Destructing };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

