/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsDeviceParameterIdentifier {
  public final static XsDeviceParameterIdentifier XDPI_Unknown = new XsDeviceParameterIdentifier("XDPI_Unknown", minimalJNI.XDPI_Unknown_get());
  public final static XsDeviceParameterIdentifier XDPI_PacketErrorRate = new XsDeviceParameterIdentifier("XDPI_PacketErrorRate", minimalJNI.XDPI_PacketErrorRate_get());
  public final static XsDeviceParameterIdentifier XDPI_ExtendedBuffer = new XsDeviceParameterIdentifier("XDPI_ExtendedBuffer", minimalJNI.XDPI_ExtendedBuffer_get());
  public final static XsDeviceParameterIdentifier XDPI_UplinkTimeout = new XsDeviceParameterIdentifier("XDPI_UplinkTimeout", minimalJNI.XDPI_UplinkTimeout_get());
  public final static XsDeviceParameterIdentifier XDPI_SyncLossTimeout = new XsDeviceParameterIdentifier("XDPI_SyncLossTimeout", minimalJNI.XDPI_SyncLossTimeout_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDeviceParameterIdentifier swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDeviceParameterIdentifier.class + " with value " + swigValue);
  }

  private XsDeviceParameterIdentifier(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDeviceParameterIdentifier(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDeviceParameterIdentifier(String swigName, XsDeviceParameterIdentifier swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDeviceParameterIdentifier[] swigValues = { XDPI_Unknown, XDPI_PacketErrorRate, XDPI_ExtendedBuffer, XDPI_UplinkTimeout, XDPI_SyncLossTimeout };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

