/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsDeviceOptionFlag {
  public final static XsDeviceOptionFlag XDOF_DisableAutoStore = new XsDeviceOptionFlag("XDOF_DisableAutoStore", minimalJNI.XDOF_DisableAutoStore_get());
  public final static XsDeviceOptionFlag XDOF_DisableAutoMeasurement = new XsDeviceOptionFlag("XDOF_DisableAutoMeasurement", minimalJNI.XDOF_DisableAutoMeasurement_get());
  public final static XsDeviceOptionFlag XDOF_EnableBeidou = new XsDeviceOptionFlag("XDOF_EnableBeidou", minimalJNI.XDOF_EnableBeidou_get());
  public final static XsDeviceOptionFlag XDOF_DisableGps = new XsDeviceOptionFlag("XDOF_DisableGps", minimalJNI.XDOF_DisableGps_get());
  public final static XsDeviceOptionFlag XDOF_EnableAhs = new XsDeviceOptionFlag("XDOF_EnableAhs", minimalJNI.XDOF_EnableAhs_get());
  public final static XsDeviceOptionFlag XDOF_EnableOrientationSmoother = new XsDeviceOptionFlag("XDOF_EnableOrientationSmoother", minimalJNI.XDOF_EnableOrientationSmoother_get());
  public final static XsDeviceOptionFlag XDOF_EnableConfigurableBusId = new XsDeviceOptionFlag("XDOF_EnableConfigurableBusId", minimalJNI.XDOF_EnableConfigurableBusId_get());
  public final static XsDeviceOptionFlag XDOF_EnableInrunCompassCalibration = new XsDeviceOptionFlag("XDOF_EnableInrunCompassCalibration", minimalJNI.XDOF_EnableInrunCompassCalibration_get());
  public final static XsDeviceOptionFlag XDOF_DisableSleepMode = new XsDeviceOptionFlag("XDOF_DisableSleepMode", minimalJNI.XDOF_DisableSleepMode_get());
  public final static XsDeviceOptionFlag XDOF_EnableConfigMessageAtStartup = new XsDeviceOptionFlag("XDOF_EnableConfigMessageAtStartup", minimalJNI.XDOF_EnableConfigMessageAtStartup_get());
  public final static XsDeviceOptionFlag XDOF_EnableColdFilterResets = new XsDeviceOptionFlag("XDOF_EnableColdFilterResets", minimalJNI.XDOF_EnableColdFilterResets_get());
  public final static XsDeviceOptionFlag XDOF_EnablePositionVelocitySmoother = new XsDeviceOptionFlag("XDOF_EnablePositionVelocitySmoother", minimalJNI.XDOF_EnablePositionVelocitySmoother_get());
  public final static XsDeviceOptionFlag XDOF_EnableContinuousZRU = new XsDeviceOptionFlag("XDOF_EnableContinuousZRU", minimalJNI.XDOF_EnableContinuousZRU_get());
  public final static XsDeviceOptionFlag XDOF_None = new XsDeviceOptionFlag("XDOF_None", minimalJNI.XDOF_None_get());
  public final static XsDeviceOptionFlag XDOF_All = new XsDeviceOptionFlag("XDOF_All", minimalJNI.XDOF_All_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsDeviceOptionFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsDeviceOptionFlag.class + " with value " + swigValue);
  }

  private XsDeviceOptionFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsDeviceOptionFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsDeviceOptionFlag(String swigName, XsDeviceOptionFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsDeviceOptionFlag[] swigValues = { XDOF_DisableAutoStore, XDOF_DisableAutoMeasurement, XDOF_EnableBeidou, XDOF_DisableGps, XDOF_EnableAhs, XDOF_EnableOrientationSmoother, XDOF_EnableConfigurableBusId, XDOF_EnableInrunCompassCalibration, XDOF_DisableSleepMode, XDOF_EnableConfigMessageAtStartup, XDOF_EnableColdFilterResets, XDOF_EnablePositionVelocitySmoother, XDOF_EnableContinuousZRU, XDOF_None, XDOF_All };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

