/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsEulerClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsEulerClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsEulerClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsEulerClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsEulerClass() {
    this(minimalJNI.new_XsEulerClass__SWIG_0(), true);
  }

  public XsEulerClass(SWIGTYPE_p_XsReal x_, SWIGTYPE_p_XsReal y_, SWIGTYPE_p_XsReal z_) {
    this(minimalJNI.new_XsEulerClass__SWIG_1(SWIGTYPE_p_XsReal.getCPtr(x_), SWIGTYPE_p_XsReal.getCPtr(y_), SWIGTYPE_p_XsReal.getCPtr(z_)), true);
  }

  public XsEulerClass(XsEulerClass other) {
    this(minimalJNI.new_XsEulerClass__SWIG_2(XsEulerClass.getCPtr(other), other), true);
  }

  public XsEulerClass(XsVectorClass other) {
    this(minimalJNI.new_XsEulerClass__SWIG_3(XsVectorClass.getCPtr(other), other), true);
  }

  public XsEulerClass(XsQuaternionClass q) {
    this(minimalJNI.new_XsEulerClass__SWIG_4(XsQuaternionClass.getCPtr(q), q), true);
  }

  public XsEulerClass opSet(XsEulerClass other) {
    return new XsEulerClass(minimalJNI.XsEulerClass_opSet(swigCPtr, this, XsEulerClass.getCPtr(other), other), false);
  }

  public SWIGTYPE_p_XsReal opSquareBracket(SWIGTYPE_p_XsSize index) {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_opSquareBracket(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index)), true);
  }

  public boolean empty() {
    return minimalJNI.XsEulerClass_empty(swigCPtr, this);
  }

  public SWIGTYPE_p_XsReal data() {
    long cPtr = minimalJNI.XsEulerClass_data(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_XsReal(cPtr, false);
  }

  public XsEulerClass fromQuaternion(XsQuaternionClass quat) {
    return new XsEulerClass(minimalJNI.XsEulerClass_fromQuaternion(swigCPtr, this, XsQuaternionClass.getCPtr(quat), quat), false);
  }

  public boolean opEquals(XsEulerClass other) {
    return minimalJNI.XsEulerClass_opEquals(swigCPtr, this, XsEulerClass.getCPtr(other), other);
  }

  public boolean opUnequals(XsEulerClass other) {
    return minimalJNI.XsEulerClass_opUnequals(swigCPtr, this, XsEulerClass.getCPtr(other), other);
  }

  public SWIGTYPE_p_XsReal roll() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_roll(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal pitch() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_pitch(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal yaw() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_yaw(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal x() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_x(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal y() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_y(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal z() {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsEulerClass_z(swigCPtr, this), true);
  }

  public boolean isEqual(XsEulerClass other, SWIGTYPE_p_XsReal tolerance) {
    return minimalJNI.XsEulerClass_isEqual(swigCPtr, this, XsEulerClass.getCPtr(other), other, SWIGTYPE_p_XsReal.getCPtr(tolerance));
  }

}
