/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsFingerData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsFingerData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsFingerData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsFingerData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsFingerData() {
    this(minimalJNI.new_XsFingerData__SWIG_0(), true);
  }

  public XsFingerData(XsQuaternionClass dq, XsVectorClass dv, XsVectorClass mag, int flags) {
    this(minimalJNI.new_XsFingerData__SWIG_1(XsQuaternionClass.getCPtr(dq), dq, XsVectorClass.getCPtr(dv), dv, XsVectorClass.getCPtr(mag), mag, flags), true);
  }

  public XsFingerData(XsFingerData other) {
    this(minimalJNI.new_XsFingerData__SWIG_2(XsFingerData.getCPtr(other), other), true);
  }

  public XsFingerData opSet(XsFingerData other) {
    return new XsFingerData(minimalJNI.XsFingerData_opSet(swigCPtr, this, XsFingerData.getCPtr(other), other), false);
  }

  public void clear() {
    minimalJNI.XsFingerData_clear(swigCPtr, this);
  }

  public XsQuaternionClass orientationIncrement() {
    return new XsQuaternionClass(minimalJNI.XsFingerData_orientationIncrement(swigCPtr, this), false);
  }

  public XsVector3 velocityIncrement() {
    return new XsVector3(minimalJNI.XsFingerData_velocityIncrement(swigCPtr, this), false);
  }

  public XsVector3 mag() {
    return new XsVector3(minimalJNI.XsFingerData_mag(swigCPtr, this), false);
  }

  public int flags() {
    return minimalJNI.XsFingerData_flags(swigCPtr, this);
  }

  public boolean opEquals(XsFingerData other) {
    return minimalJNI.XsFingerData_opEquals(swigCPtr, this, XsFingerData.getCPtr(other), other);
  }

  public boolean opUnequals(XsFingerData other) {
    return minimalJNI.XsFingerData_opUnequals(swigCPtr, this, XsFingerData.getCPtr(other), other);
  }

  public void swap(XsFingerData other) {
    minimalJNI.XsFingerData_swap(swigCPtr, this, XsFingerData.getCPtr(other), other);
  }

}
