/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsHandId {
  public final static XsHandId XHI_LeftHand = new XsHandId("XHI_LeftHand", minimalJNI.XHI_LeftHand_get());
  public final static XsHandId XHI_RightHand = new XsHandId("XHI_RightHand", minimalJNI.XHI_RightHand_get());
  public final static XsHandId XHI_Unknown = new XsHandId("XHI_Unknown");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsHandId swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsHandId.class + " with value " + swigValue);
  }

  private XsHandId(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsHandId(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsHandId(String swigName, XsHandId swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsHandId[] swigValues = { XHI_LeftHand, XHI_RightHand, XHI_Unknown };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

