/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsMatrixClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMatrixClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMatrixClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsMatrixClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_XsReal getM_data() {
    long cPtr = minimalJNI.XsMatrixClass_m_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_XsReal(cPtr, false);
  }

  public SWIGTYPE_p_XsSize getM_rows() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_m_rows_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize getM_cols() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_m_cols_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize getM_stride() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_m_stride_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize getM_flags() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_m_flags_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize flags() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_flags(swigCPtr, this), true);
  }

  public XsMatrixClass(SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols, SWIGTYPE_p_XsSize strde, SWIGTYPE_p_XsReal dat) {
    this(minimalJNI.new_XsMatrixClass__SWIG_0(SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols), SWIGTYPE_p_XsSize.getCPtr(strde), SWIGTYPE_p_XsReal.getCPtr(dat)), true);
  }

  public XsMatrixClass(SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols, SWIGTYPE_p_XsSize strde) {
    this(minimalJNI.new_XsMatrixClass__SWIG_1(SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols), SWIGTYPE_p_XsSize.getCPtr(strde)), true);
  }

  public XsMatrixClass(SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols) {
    this(minimalJNI.new_XsMatrixClass__SWIG_2(SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols)), true);
  }

  public XsMatrixClass(SWIGTYPE_p_XsSize rows) {
    this(minimalJNI.new_XsMatrixClass__SWIG_3(SWIGTYPE_p_XsSize.getCPtr(rows)), true);
  }

  public XsMatrixClass() {
    this(minimalJNI.new_XsMatrixClass__SWIG_4(), true);
  }

  public XsMatrixClass(XsMatrixClass other) {
    this(minimalJNI.new_XsMatrixClass__SWIG_5(XsMatrixClass.getCPtr(other), other), true);
  }

  public XsMatrixClass(SWIGTYPE_p_XsReal ref, SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols, SWIGTYPE_p_XsSize stride, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsMatrixClass__SWIG_6(SWIGTYPE_p_XsReal.getCPtr(ref), SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols), SWIGTYPE_p_XsSize.getCPtr(stride), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

  public XsMatrixClass(XsMatrixClass other, SWIGTYPE_p_XsReal ref, SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols, SWIGTYPE_p_XsSize stride, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsMatrixClass__SWIG_7(XsMatrixClass.getCPtr(other), other, SWIGTYPE_p_XsReal.getCPtr(ref), SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols), SWIGTYPE_p_XsSize.getCPtr(stride), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

  public XsMatrixClass(XsQuaternionClass quat) {
    this(minimalJNI.new_XsMatrixClass__SWIG_8(XsQuaternionClass.getCPtr(quat), quat), true);
  }

  public void setSize(SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols, SWIGTYPE_p_XsSize stride) {
    minimalJNI.XsMatrixClass_setSize__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols), SWIGTYPE_p_XsSize.getCPtr(stride));
  }

  public void setSize(SWIGTYPE_p_XsSize rows, SWIGTYPE_p_XsSize cols) {
    minimalJNI.XsMatrixClass_setSize__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(rows), SWIGTYPE_p_XsSize.getCPtr(cols));
  }

  public XsMatrixClass opSet(XsMatrixClass other) {
    return new XsMatrixClass(minimalJNI.XsMatrixClass_opSet(swigCPtr, this, XsMatrixClass.getCPtr(other), other), false);
  }

  public boolean empty() {
    return minimalJNI.XsMatrixClass_empty(swigCPtr, this);
  }

  public void setZero() {
    minimalJNI.XsMatrixClass_setZero(swigCPtr, this);
  }

  public SWIGTYPE_p_XsSize offset(SWIGTYPE_p_XsSize row, SWIGTYPE_p_XsSize column) {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_offset(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(row), SWIGTYPE_p_XsSize.getCPtr(column)), true);
  }

  public SWIGTYPE_p_XsReal value(SWIGTYPE_p_XsSize row, SWIGTYPE_p_XsSize column) {
    return new SWIGTYPE_p_XsReal(minimalJNI.XsMatrixClass_value(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(row), SWIGTYPE_p_XsSize.getCPtr(column)), true);
  }

  public void setValue(SWIGTYPE_p_XsSize row, SWIGTYPE_p_XsSize column, SWIGTYPE_p_XsReal value) {
    minimalJNI.XsMatrixClass_setValue(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(row), SWIGTYPE_p_XsSize.getCPtr(column), SWIGTYPE_p_XsReal.getCPtr(value));
  }

  public SWIGTYPE_p_XsReal opSquareBracket(SWIGTYPE_p_XsSize row) {
    long cPtr = minimalJNI.XsMatrixClass_opSquareBracket(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(row));
    return (cPtr == 0) ? null : new SWIGTYPE_p_XsReal(cPtr, false);
  }

  public XsMatrixClass opMult(SWIGTYPE_p_XsReal scalar) {
    return new XsMatrixClass(minimalJNI.XsMatrixClass_opMult(swigCPtr, this, SWIGTYPE_p_XsReal.getCPtr(scalar)), true);
  }

  public XsMatrixClass fromQuaternion(XsQuaternionClass quat) {
    return new XsMatrixClass(minimalJNI.XsMatrixClass_fromQuaternion(swigCPtr, this, XsQuaternionClass.getCPtr(quat), quat), false);
  }

  public void zero() {
    minimalJNI.XsMatrixClass_zero(swigCPtr, this);
  }

  public SWIGTYPE_p_XsSize rows() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_rows(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize cols() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_cols(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize stride() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMatrixClass_stride(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsReal data() {
    long cPtr = minimalJNI.XsMatrixClass_data(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_XsReal(cPtr, false);
  }

  public boolean opEquals(XsMatrixClass other) {
    return minimalJNI.XsMatrixClass_opEquals(swigCPtr, this, XsMatrixClass.getCPtr(other), other);
  }

  public boolean isEqual(XsMatrixClass other, SWIGTYPE_p_XsReal tolerance) {
    return minimalJNI.XsMatrixClass_isEqual(swigCPtr, this, XsMatrixClass.getCPtr(other), other, SWIGTYPE_p_XsReal.getCPtr(tolerance));
  }

  public void swap(XsMatrixClass b) {
    minimalJNI.XsMatrixClass_swap(swigCPtr, this, XsMatrixClass.getCPtr(b), b);
  }

}
