/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsMessageClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMessageClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMessageClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsMessageClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsMessageClass(XsXbusMessageId msgId, SWIGTYPE_p_XsSize dataLength) {
    this(minimalJNI.new_XsMessageClass__SWIG_0(msgId.swigValue(), SWIGTYPE_p_XsSize.getCPtr(dataLength)), true);
  }

  public XsMessageClass(XsXbusMessageId msgId) {
    this(minimalJNI.new_XsMessageClass__SWIG_1(msgId.swigValue()), true);
  }

  public XsMessageClass() {
    this(minimalJNI.new_XsMessageClass__SWIG_2(), true);
  }

  public XsMessageClass(SWIGTYPE_p_unsigned_char source, SWIGTYPE_p_XsSize size) {
    this(minimalJNI.new_XsMessageClass__SWIG_3(SWIGTYPE_p_unsigned_char.getCPtr(source), SWIGTYPE_p_XsSize.getCPtr(size)), true);
  }

  public XsMessageClass(XsStringClass source, boolean computeChecksum) {
    this(minimalJNI.new_XsMessageClass__SWIG_4(XsStringClass.getCPtr(source), source, computeChecksum), true);
  }

  public XsMessageClass(XsStringClass source) {
    this(minimalJNI.new_XsMessageClass__SWIG_5(XsStringClass.getCPtr(source), source), true);
  }

  public XsMessageClass(XsMessageClass src) {
    this(minimalJNI.new_XsMessageClass__SWIG_6(XsMessageClass.getCPtr(src), src), true);
  }

  public void clear() {
    minimalJNI.XsMessageClass_clear(swigCPtr, this);
  }

  public boolean empty() {
    return minimalJNI.XsMessageClass_empty(swigCPtr, this);
  }

  public short getBusId() {
    return minimalJNI.XsMessageClass_getBusId(swigCPtr, this);
  }

  public SWIGTYPE_p_unsigned_char getDataBuffer(SWIGTYPE_p_XsSize offset) {
    long cPtr = minimalJNI.XsMessageClass_getDataBuffer__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_unsigned_char getDataBuffer() {
    long cPtr = minimalJNI.XsMessageClass_getDataBuffer__SWIG_1(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public short getDataByte(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataByte__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public short getDataByte() {
    return minimalJNI.XsMessageClass_getDataByte__SWIG_1(swigCPtr, this);
  }

  public double getDataDouble(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataDouble__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public double getDataDouble() {
    return minimalJNI.XsMessageClass_getDataDouble__SWIG_1(swigCPtr, this);
  }

  public float getDataFloat(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataFloat__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public float getDataFloat() {
    return minimalJNI.XsMessageClass_getDataFloat__SWIG_1(swigCPtr, this);
  }

  public double getDataF1220(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataF1220__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public double getDataF1220() {
    return minimalJNI.XsMessageClass_getDataF1220__SWIG_1(swigCPtr, this);
  }

  public double getDataFP1632(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataFP1632__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public double getDataFP1632() {
    return minimalJNI.XsMessageClass_getDataFP1632__SWIG_1(swigCPtr, this);
  }

  public long getDataLong(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataLong__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public long getDataLong() {
    return minimalJNI.XsMessageClass_getDataLong__SWIG_1(swigCPtr, this);
  }

  public java.math.BigInteger getDataLongLong(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataLongLong__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public java.math.BigInteger getDataLongLong() {
    return minimalJNI.XsMessageClass_getDataLongLong__SWIG_1(swigCPtr, this);
  }

  public int getDataShort(SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataShort__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public int getDataShort() {
    return minimalJNI.XsMessageClass_getDataShort__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_XsSize getDataSize() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMessageClass_getDataSize(swigCPtr, this), true);
  }

  public XsXbusMessageId getMessageId() {
    return XsXbusMessageId.swigToEnum(minimalJNI.XsMessageClass_getMessageId(swigCPtr, this));
  }

  public XsResultValue toResultValue() {
    return XsResultValue.swigToEnum(minimalJNI.XsMessageClass_toResultValue(swigCPtr, this));
  }

  public SWIGTYPE_p_unsigned_char getMessageStart() {
    long cPtr = minimalJNI.XsMessageClass_getMessageStart(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public SWIGTYPE_p_XsSize getTotalMessageSize() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsMessageClass_getTotalMessageSize(swigCPtr, this), true);
  }

  public boolean isChecksumOk() {
    return minimalJNI.XsMessageClass_isChecksumOk(swigCPtr, this);
  }

  public boolean loadFromString(SWIGTYPE_p_unsigned_char src, SWIGTYPE_p_XsSize msgSize) {
    return minimalJNI.XsMessageClass_loadFromString(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(src), SWIGTYPE_p_XsSize.getCPtr(msgSize));
  }

  public void recomputeChecksum() {
    minimalJNI.XsMessageClass_recomputeChecksum(swigCPtr, this);
  }

  public void resizeData(SWIGTYPE_p_XsSize newSize) {
    minimalJNI.XsMessageClass_resizeData(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(newSize));
  }

  public void setBusId(short busId) {
    minimalJNI.XsMessageClass_setBusId__SWIG_0(swigCPtr, this, busId);
  }

  public void setBusId(int busId) {
    minimalJNI.XsMessageClass_setBusId__SWIG_1(swigCPtr, this, busId);
  }

  public void setDataBuffer(SWIGTYPE_p_unsigned_char buffer, SWIGTYPE_p_XsSize size, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataBuffer__SWIG_0(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buffer), SWIGTYPE_p_XsSize.getCPtr(size), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataBuffer(SWIGTYPE_p_unsigned_char buffer, SWIGTYPE_p_XsSize size) {
    minimalJNI.XsMessageClass_setDataBuffer__SWIG_1(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(buffer), SWIGTYPE_p_XsSize.getCPtr(size));
  }

  public void setDataByte(short value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataByte__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataByte(short value) {
    minimalJNI.XsMessageClass_setDataByte__SWIG_1(swigCPtr, this, value);
  }

  public void setDataDouble(double value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataDouble__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataDouble(double value) {
    minimalJNI.XsMessageClass_setDataDouble__SWIG_1(swigCPtr, this, value);
  }

  public void setDataFloat(float value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataFloat__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataFloat(float value) {
    minimalJNI.XsMessageClass_setDataFloat__SWIG_1(swigCPtr, this, value);
  }

  public void setDataF1220(double value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataF1220__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataF1220(double value) {
    minimalJNI.XsMessageClass_setDataF1220__SWIG_1(swigCPtr, this, value);
  }

  public void setDataFP1632(double value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataFP1632__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataFP1632(double value) {
    minimalJNI.XsMessageClass_setDataFP1632__SWIG_1(swigCPtr, this, value);
  }

  public void setDataLong(long value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataLong__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataLong(long value) {
    minimalJNI.XsMessageClass_setDataLong__SWIG_1(swigCPtr, this, value);
  }

  public void setDataLongLong(java.math.BigInteger value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataLongLong__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataLongLong(java.math.BigInteger value) {
    minimalJNI.XsMessageClass_setDataLongLong__SWIG_1(swigCPtr, this, value);
  }

  public void setDataShort(int value, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataShort__SWIG_0(swigCPtr, this, value, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataShort(int value) {
    minimalJNI.XsMessageClass_setDataShort__SWIG_1(swigCPtr, this, value);
  }

  public void setMessageId(XsXbusMessageId msgId) {
    minimalJNI.XsMessageClass_setMessageId(swigCPtr, this, msgId.swigValue());
  }

  public XsMessageClass opSet(XsMessageClass src) {
    return new XsMessageClass(minimalJNI.XsMessageClass_opSet(swigCPtr, this, XsMessageClass.getCPtr(src), src), false);
  }

  public void deleteData(SWIGTYPE_p_XsSize count, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_deleteData__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void deleteData(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsMessageClass_deleteData__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void insertData(SWIGTYPE_p_XsSize count, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_insertData__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void insertData(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsMessageClass_insertData__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public static short getFPValueSize(XsDataIdentifier id) {
    return minimalJNI.XsMessageClass_getFPValueSize(id.swigValue());
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest, SWIGTYPE_p_XsSize offset, SWIGTYPE_p_XsSize numValues) {
    minimalJNI.XsMessageClass_getDataFPValue__SWIG_0(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest), SWIGTYPE_p_XsSize.getCPtr(offset), SWIGTYPE_p_XsSize.getCPtr(numValues));
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_getDataFPValue__SWIG_1(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double dest) {
    minimalJNI.XsMessageClass_getDataFPValue__SWIG_2(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(dest));
  }

  public double getDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_XsSize offset) {
    return minimalJNI.XsMessageClass_getDataFPValue__SWIG_3(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public double getDataFPValue(XsDataIdentifier dataIdentifier) {
    return minimalJNI.XsMessageClass_getDataFPValue__SWIG_4(swigCPtr, this, dataIdentifier.swigValue());
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data, SWIGTYPE_p_XsSize offset, SWIGTYPE_p_XsSize numValues) {
    minimalJNI.XsMessageClass_setDataFPValue__SWIG_0(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data), SWIGTYPE_p_XsSize.getCPtr(offset), SWIGTYPE_p_XsSize.getCPtr(numValues));
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataFPValue__SWIG_1(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data), SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, SWIGTYPE_p_double data) {
    minimalJNI.XsMessageClass_setDataFPValue__SWIG_2(swigCPtr, this, dataIdentifier.swigValue(), SWIGTYPE_p_double.getCPtr(data));
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, double data, SWIGTYPE_p_XsSize offset) {
    minimalJNI.XsMessageClass_setDataFPValue__SWIG_3(swigCPtr, this, dataIdentifier.swigValue(), data, SWIGTYPE_p_XsSize.getCPtr(offset));
  }

  public void setDataFPValue(XsDataIdentifier dataIdentifier, double data) {
    minimalJNI.XsMessageClass_setDataFPValue__SWIG_4(swigCPtr, this, dataIdentifier.swigValue(), data);
  }

  public boolean opEquals(XsMessageClass other) {
    return minimalJNI.XsMessageClass_opEquals(swigCPtr, this, XsMessageClass.getCPtr(other), other);
  }

  public SWIGTYPE_p_XsByteArray rawMessage() {
    return new SWIGTYPE_p_XsByteArray(minimalJNI.XsMessageClass_rawMessage(swigCPtr, this), false);
  }

  public XsStringClass toHexString(SWIGTYPE_p_XsSize maxBytes) {
    return new XsStringClass(minimalJNI.XsMessageClass_toHexString__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(maxBytes)), true);
  }

  public XsStringClass toHexString() {
    return new XsStringClass(minimalJNI.XsMessageClass_toHexString__SWIG_1(swigCPtr, this), true);
  }

}
