/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsMessageHeader {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMessageHeader(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMessageHeader obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsMessageHeader(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_preamble(short value) {
    minimalJNI.XsMessageHeader_m_preamble_set(swigCPtr, this, value);
  }

  public short getM_preamble() {
    return minimalJNI.XsMessageHeader_m_preamble_get(swigCPtr, this);
  }

  public void setM_busId(short value) {
    minimalJNI.XsMessageHeader_m_busId_set(swigCPtr, this, value);
  }

  public short getM_busId() {
    return minimalJNI.XsMessageHeader_m_busId_get(swigCPtr, this);
  }

  public void setM_messageId(short value) {
    minimalJNI.XsMessageHeader_m_messageId_set(swigCPtr, this, value);
  }

  public short getM_messageId() {
    return minimalJNI.XsMessageHeader_m_messageId_get(swigCPtr, this);
  }

  public void setM_length(short value) {
    minimalJNI.XsMessageHeader_m_length_set(swigCPtr, this, value);
  }

  public short getM_length() {
    return minimalJNI.XsMessageHeader_m_length_get(swigCPtr, this);
  }

  static public class LengthData {
    private transient long swigCPtr;
    protected transient boolean swigCMemOwn;
  
    protected LengthData(long cPtr, boolean cMemoryOwn) {
      swigCMemOwn = cMemoryOwn;
      swigCPtr = cPtr;
    }
  
    protected static long getCPtr(LengthData obj) {
      return (obj == null) ? 0 : obj.swigCPtr;
    }
  
    @SuppressWarnings("deprecation")
    protected void finalize() {
      delete();
    }
  
    public synchronized void delete() {
      if (swigCPtr != 0) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          minimalJNI.delete_XsMessageHeader_LengthData(swigCPtr);
        }
        swigCPtr = 0;
      }
    }
  
      static public class ExtendedLength {
        private transient long swigCPtr;
        protected transient boolean swigCMemOwn;
      
        protected ExtendedLength(long cPtr, boolean cMemoryOwn) {
          swigCMemOwn = cMemoryOwn;
          swigCPtr = cPtr;
        }
      
        protected static long getCPtr(ExtendedLength obj) {
          return (obj == null) ? 0 : obj.swigCPtr;
        }
      
        @SuppressWarnings("deprecation")
        protected void finalize() {
          delete();
        }
      
        public synchronized void delete() {
          if (swigCPtr != 0) {
            if (swigCMemOwn) {
              swigCMemOwn = false;
              minimalJNI.delete_XsMessageHeader_LengthData_ExtendedLength(swigCPtr);
            }
            swigCPtr = 0;
          }
        }
      
            static public class ExtendedParts {
              private transient long swigCPtr;
              protected transient boolean swigCMemOwn;
            
              protected ExtendedParts(long cPtr, boolean cMemoryOwn) {
                swigCMemOwn = cMemoryOwn;
                swigCPtr = cPtr;
              }
            
              protected static long getCPtr(ExtendedParts obj) {
                return (obj == null) ? 0 : obj.swigCPtr;
              }
            
              @SuppressWarnings("deprecation")
              protected void finalize() {
                delete();
              }
            
              public synchronized void delete() {
                if (swigCPtr != 0) {
                  if (swigCMemOwn) {
                    swigCMemOwn = false;
                    minimalJNI.delete_XsMessageHeader_LengthData_ExtendedLength_ExtendedParts(swigCPtr);
                  }
                  swigCPtr = 0;
                }
              }
            
              public void setM_high(short value) {
                minimalJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_high_set(swigCPtr, this, value);
              }
            
              public short getM_high() {
                return minimalJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_high_get(swigCPtr, this);
              }
            
              public void setM_low(short value) {
                minimalJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_low_set(swigCPtr, this, value);
              }
            
              public short getM_low() {
                return minimalJNI.XsMessageHeader_LengthData_ExtendedLength_ExtendedParts_m_low_get(swigCPtr, this);
              }
            
              public ExtendedParts() {
                this(minimalJNI.new_XsMessageHeader_LengthData_ExtendedLength_ExtendedParts(), true);
              }
            
            }
      
        public void setM_length(XsMessageHeader.LengthData.ExtendedLength.ExtendedParts value) {
          minimalJNI.XsMessageHeader_LengthData_ExtendedLength_m_length_set(swigCPtr, this, XsMessageHeader.LengthData.ExtendedLength.ExtendedParts.getCPtr(value), value);
        }
      
        public XsMessageHeader.LengthData.ExtendedLength.ExtendedParts getM_length() {
          long cPtr = minimalJNI.XsMessageHeader_LengthData_ExtendedLength_m_length_get(swigCPtr, this);
          return (cPtr == 0) ? null : new XsMessageHeader.LengthData.ExtendedLength.ExtendedParts(cPtr, false);
        }
      
        public void setM_data(SWIGTYPE_p_unsigned_char value) {
          minimalJNI.XsMessageHeader_LengthData_ExtendedLength_m_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
        }
      
        public SWIGTYPE_p_unsigned_char getM_data() {
          long cPtr = minimalJNI.XsMessageHeader_LengthData_ExtendedLength_m_data_get(swigCPtr, this);
          return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
        }
      
        public ExtendedLength() {
          this(minimalJNI.new_XsMessageHeader_LengthData_ExtendedLength(), true);
        }
      
      }
  
    public void setM_extended(XsMessageHeader.LengthData.ExtendedLength value) {
      minimalJNI.XsMessageHeader_LengthData_m_extended_set(swigCPtr, this, XsMessageHeader.LengthData.ExtendedLength.getCPtr(value), value);
    }
  
    public XsMessageHeader.LengthData.ExtendedLength getM_extended() {
      long cPtr = minimalJNI.XsMessageHeader_LengthData_m_extended_get(swigCPtr, this);
      return (cPtr == 0) ? null : new XsMessageHeader.LengthData.ExtendedLength(cPtr, false);
    }
  
    public void setM_data(SWIGTYPE_p_unsigned_char value) {
      minimalJNI.XsMessageHeader_LengthData_m_data_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
    }
  
    public SWIGTYPE_p_unsigned_char getM_data() {
      long cPtr = minimalJNI.XsMessageHeader_LengthData_m_data_get(swigCPtr, this);
      return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
    }
  
    public LengthData() {
      this(minimalJNI.new_XsMessageHeader_LengthData(), true);
    }
  
  }

  public void setM_datlen(XsMessageHeader.LengthData value) {
    minimalJNI.XsMessageHeader_m_datlen_set(swigCPtr, this, XsMessageHeader.LengthData.getCPtr(value), value);
  }

  public XsMessageHeader.LengthData getM_datlen() {
    long cPtr = minimalJNI.XsMessageHeader_m_datlen_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsMessageHeader.LengthData(cPtr, false);
  }

  public XsMessageHeader() {
    this(minimalJNI.new_XsMessageHeader(), true);
  }

}
