/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsOption {
  public final static XsOption XSO_None = new XsOption("XSO_None", minimalJNI.XSO_None_get());
  public final static XsOption XSO_Calibrate = new XsOption("XSO_Calibrate", minimalJNI.XSO_Calibrate_get());
  public final static XsOption XSO_Orientation = new XsOption("XSO_Orientation", minimalJNI.XSO_Orientation_get());
  public final static XsOption XSO_KeepLastLiveData = new XsOption("XSO_KeepLastLiveData", minimalJNI.XSO_KeepLastLiveData_get());
  public final static XsOption XSO_RetainLiveData = new XsOption("XSO_RetainLiveData", minimalJNI.XSO_RetainLiveData_get());
  public final static XsOption XSO_RetainBufferedData = new XsOption("XSO_RetainBufferedData", minimalJNI.XSO_RetainBufferedData_get());
  public final static XsOption XSO_OrientationInLiveStream = new XsOption("XSO_OrientationInLiveStream", minimalJNI.XSO_OrientationInLiveStream_get());
  public final static XsOption XSO_OrientationInBufferedStream = new XsOption("XSO_OrientationInBufferedStream", minimalJNI.XSO_OrientationInBufferedStream_get());
  public final static XsOption XSO_ApplyOrientationResetToCalData = new XsOption("XSO_ApplyOrientationResetToCalData", minimalJNI.XSO_ApplyOrientationResetToCalData_get());
  public final static XsOption XSO_InterpolateMissingData = new XsOption("XSO_InterpolateMissingData", minimalJNI.XSO_InterpolateMissingData_get());
  public final static XsOption XSO_SkipDataBundling = new XsOption("XSO_SkipDataBundling", minimalJNI.XSO_SkipDataBundling_get());
  public final static XsOption XSO_ExpectNoRetransmissionsInFile = new XsOption("XSO_ExpectNoRetransmissionsInFile", minimalJNI.XSO_ExpectNoRetransmissionsInFile_get());
  public final static XsOption XSO_Reserved = new XsOption("XSO_Reserved", minimalJNI.XSO_Reserved_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsOption swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsOption.class + " with value " + swigValue);
  }

  private XsOption(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsOption(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsOption(String swigName, XsOption swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsOption[] swigValues = { XSO_None, XSO_Calibrate, XSO_Orientation, XSO_KeepLastLiveData, XSO_RetainLiveData, XSO_RetainBufferedData, XSO_OrientationInLiveStream, XSO_OrientationInBufferedStream, XSO_ApplyOrientationResetToCalData, XSO_InterpolateMissingData, XSO_SkipDataBundling, XSO_ExpectNoRetransmissionsInFile, XSO_Reserved };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

