/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsProtocolType {
  public final static XsProtocolType XPT_Xbus = new XsProtocolType("XPT_Xbus", minimalJNI.XPT_Xbus_get());
  public final static XsProtocolType XPT_Nmea = new XsProtocolType("XPT_Nmea");
  public final static XsProtocolType XPT_ImarFsas = new XsProtocolType("XPT_ImarFsas");
  public final static XsProtocolType XPT_ImarIfog = new XsProtocolType("XPT_ImarIfog");
  public final static XsProtocolType XPT_ImarIfogUart = new XsProtocolType("XPT_ImarIfogUart");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsProtocolType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsProtocolType.class + " with value " + swigValue);
  }

  private XsProtocolType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsProtocolType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsProtocolType(String swigName, XsProtocolType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsProtocolType[] swigValues = { XPT_Xbus, XPT_Nmea, XPT_ImarFsas, XPT_ImarIfog, XPT_ImarIfogUart };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

