/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsPressure {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsPressure(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsPressure obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsPressure(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsPressure() {
    this(minimalJNI.new_XsPressure__SWIG_0(), true);
  }

  public XsPressure(double pressure, short age) {
    this(minimalJNI.new_XsPressure__SWIG_1(pressure, age), true);
  }

  public XsPressure(double pressure) {
    this(minimalJNI.new_XsPressure__SWIG_2(pressure), true);
  }

  public XsPressure(XsPressure other) {
    this(minimalJNI.new_XsPressure__SWIG_3(XsPressure.getCPtr(other), other), true);
  }

  public XsPressure opSet(XsPressure other) {
    return new XsPressure(minimalJNI.XsPressure_opSet(swigCPtr, this, XsPressure.getCPtr(other), other), false);
  }

  public boolean opEquals(XsPressure other) {
    return minimalJNI.XsPressure_opEquals(swigCPtr, this, XsPressure.getCPtr(other), other);
  }

  public boolean opUnequals(XsPressure other) {
    return minimalJNI.XsPressure_opUnequals(swigCPtr, this, XsPressure.getCPtr(other), other);
  }

  public void setM_pressure(double value) {
    minimalJNI.XsPressure_m_pressure_set(swigCPtr, this, value);
  }

  public double getM_pressure() {
    return minimalJNI.XsPressure_m_pressure_get(swigCPtr, this);
  }

  public void setM_pressureAge(short value) {
    minimalJNI.XsPressure_m_pressureAge_set(swigCPtr, this, value);
  }

  public short getM_pressureAge() {
    return minimalJNI.XsPressure_m_pressureAge_get(swigCPtr, this);
  }

}
