/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsSatInfo {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsSatInfo(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsSatInfo obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsSatInfo(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_gnssId(short value) {
    minimalJNI.XsSatInfo_m_gnssId_set(swigCPtr, this, value);
  }

  public short getM_gnssId() {
    return minimalJNI.XsSatInfo_m_gnssId_get(swigCPtr, this);
  }

  public void setM_svId(short value) {
    minimalJNI.XsSatInfo_m_svId_set(swigCPtr, this, value);
  }

  public short getM_svId() {
    return minimalJNI.XsSatInfo_m_svId_get(swigCPtr, this);
  }

  public void setM_cno(short value) {
    minimalJNI.XsSatInfo_m_cno_set(swigCPtr, this, value);
  }

  public short getM_cno() {
    return minimalJNI.XsSatInfo_m_cno_get(swigCPtr, this);
  }

  public void setM_flags(short value) {
    minimalJNI.XsSatInfo_m_flags_set(swigCPtr, this, value);
  }

  public short getM_flags() {
    return minimalJNI.XsSatInfo_m_flags_get(swigCPtr, this);
  }

  public XsSatInfo() {
    this(minimalJNI.new_XsSatInfo(), true);
  }

}
