/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsScrData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsScrData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsScrData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsScrData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_acc(XsUShortVector value) {
    minimalJNI.XsScrData_m_acc_set(swigCPtr, this, XsUShortVector.getCPtr(value), value);
  }

  public XsUShortVector getM_acc() {
    long cPtr = minimalJNI.XsScrData_m_acc_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsUShortVector(cPtr, false);
  }

  public void setM_gyr(XsUShortVector value) {
    minimalJNI.XsScrData_m_gyr_set(swigCPtr, this, XsUShortVector.getCPtr(value), value);
  }

  public XsUShortVector getM_gyr() {
    long cPtr = minimalJNI.XsScrData_m_gyr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsUShortVector(cPtr, false);
  }

  public void setM_mag(XsUShortVector value) {
    minimalJNI.XsScrData_m_mag_set(swigCPtr, this, XsUShortVector.getCPtr(value), value);
  }

  public XsUShortVector getM_mag() {
    long cPtr = minimalJNI.XsScrData_m_mag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsUShortVector(cPtr, false);
  }

  public void setM_temp(int value) {
    minimalJNI.XsScrData_m_temp_set(swigCPtr, this, value);
  }

  public int getM_temp() {
    return minimalJNI.XsScrData_m_temp_get(swigCPtr, this);
  }

  public XsScrData() {
    this(minimalJNI.new_XsScrData(), true);
  }

}
