/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsStringOutputType {
  public final static XsStringOutputType XSOT_None = new XsStringOutputType("XSOT_None", minimalJNI.XSOT_None_get());
  public final static XsStringOutputType XSOT_HCHDM = new XsStringOutputType("XSOT_HCHDM", minimalJNI.XSOT_HCHDM_get());
  public final static XsStringOutputType XSOT_HCHDG = new XsStringOutputType("XSOT_HCHDG", minimalJNI.XSOT_HCHDG_get());
  public final static XsStringOutputType XSOT_TSS2 = new XsStringOutputType("XSOT_TSS2", minimalJNI.XSOT_TSS2_get());
  public final static XsStringOutputType XSOT_PHTRO = new XsStringOutputType("XSOT_PHTRO", minimalJNI.XSOT_PHTRO_get());
  public final static XsStringOutputType XSOT_PRDID = new XsStringOutputType("XSOT_PRDID", minimalJNI.XSOT_PRDID_get());
  public final static XsStringOutputType XSOT_EM1000 = new XsStringOutputType("XSOT_EM1000", minimalJNI.XSOT_EM1000_get());
  public final static XsStringOutputType XSOT_PSONCMS = new XsStringOutputType("XSOT_PSONCMS", minimalJNI.XSOT_PSONCMS_get());
  public final static XsStringOutputType XSOT_HCMTW = new XsStringOutputType("XSOT_HCMTW", minimalJNI.XSOT_HCMTW_get());
  public final static XsStringOutputType XSOT_HEHDT = new XsStringOutputType("XSOT_HEHDT", minimalJNI.XSOT_HEHDT_get());
  public final static XsStringOutputType XSOT_HEROT = new XsStringOutputType("XSOT_HEROT", minimalJNI.XSOT_HEROT_get());
  public final static XsStringOutputType XSOT_GPGGA = new XsStringOutputType("XSOT_GPGGA", minimalJNI.XSOT_GPGGA_get());
  public final static XsStringOutputType XSOT_PTCF = new XsStringOutputType("XSOT_PTCF", minimalJNI.XSOT_PTCF_get());
  public final static XsStringOutputType XSOT_XSVEL = new XsStringOutputType("XSOT_XSVEL", minimalJNI.XSOT_XSVEL_get());
  public final static XsStringOutputType XSOT_GPZDA = new XsStringOutputType("XSOT_GPZDA", minimalJNI.XSOT_GPZDA_get());
  public final static XsStringOutputType XSOT_GPRMC = new XsStringOutputType("XSOT_GPRMC", minimalJNI.XSOT_GPRMC_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsStringOutputType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsStringOutputType.class + " with value " + swigValue);
  }

  private XsStringOutputType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsStringOutputType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsStringOutputType(String swigName, XsStringOutputType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsStringOutputType[] swigValues = { XSOT_None, XSOT_HCHDM, XSOT_HCHDG, XSOT_TSS2, XSOT_PHTRO, XSOT_PRDID, XSOT_EM1000, XSOT_PSONCMS, XSOT_HCMTW, XSOT_HEHDT, XSOT_HEROT, XSOT_GPGGA, XSOT_PTCF, XSOT_XSVEL, XSOT_GPZDA, XSOT_GPRMC };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

