/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public final class XsSyncRole {
  public final static XsSyncRole XSR_Slave = new XsSyncRole("XSR_Slave");
  public final static XsSyncRole XSR_None = new XsSyncRole("XSR_None");
  public final static XsSyncRole XSR_MasterSlave = new XsSyncRole("XSR_MasterSlave");
  public final static XsSyncRole XSR_Master = new XsSyncRole("XSR_Master");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsSyncRole swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsSyncRole.class + " with value " + swigValue);
  }

  private XsSyncRole(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsSyncRole(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsSyncRole(String swigName, XsSyncRole swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsSyncRole[] swigValues = { XSR_Slave, XSR_None, XSR_MasterSlave, XSR_Master };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

