/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class XsTimeStampClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsTimeStampClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsTimeStampClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsTimeStampClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsTimeStampClass(long t) {
    this(minimalJNI.new_XsTimeStampClass__SWIG_0(t), true);
  }

  public XsTimeStampClass() {
    this(minimalJNI.new_XsTimeStampClass__SWIG_1(), true);
  }

  public XsTimeStampClass(int t) {
    this(minimalJNI.new_XsTimeStampClass__SWIG_2(t), true);
  }

  public XsTimeStampClass(double t) {
    this(minimalJNI.new_XsTimeStampClass__SWIG_3(t), true);
  }

  public XsTimeStampClass(XsTimeStampClass other) {
    this(minimalJNI.new_XsTimeStampClass__SWIG_4(XsTimeStampClass.getCPtr(other), other), true);
  }

  public XsTimeStampClass(XsTimeInfo info) {
    this(minimalJNI.new_XsTimeStampClass__SWIG_5(XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeInfo toTimeInfo() {
    return new XsTimeInfo(minimalJNI.XsTimeStampClass_toTimeInfo__SWIG_0(swigCPtr, this), true);
  }

  public void toTimeInfo(XsTimeInfo info) {
    minimalJNI.XsTimeStampClass_toTimeInfo__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info);
  }

  public XsStringClass toString() {
    return new XsStringClass(minimalJNI.XsTimeStampClass_toString(swigCPtr, this), true);
  }

  public XsTimeStampClass opSet(XsTimeStampClass other) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opSet(swigCPtr, this, XsTimeStampClass.getCPtr(other), other), false);
  }

  public long msTime() {
    return minimalJNI.XsTimeStampClass_msTime(swigCPtr, this);
  }

  public void setMsTime(long t) {
    minimalJNI.XsTimeStampClass_setMsTime(swigCPtr, this, t);
  }

  public double timeOfDay() {
    return minimalJNI.XsTimeStampClass_timeOfDay(swigCPtr, this);
  }

  public long msTimeOfDay() {
    return minimalJNI.XsTimeStampClass_msTimeOfDay(swigCPtr, this);
  }

  public double secTime() {
    return minimalJNI.XsTimeStampClass_secTime(swigCPtr, this);
  }

  public void setSecTime(double t) {
    minimalJNI.XsTimeStampClass_setSecTime(swigCPtr, this, t);
  }

  public XsTimeStampClass opPlus(XsTimeStampClass other) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opPlus(swigCPtr, this, XsTimeStampClass.getCPtr(other), other), true);
  }

  public XsTimeStampClass opSubtract(XsTimeStampClass other) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opSubtract(swigCPtr, this, XsTimeStampClass.getCPtr(other), other), true);
  }

  public XsTimeStampClass opPlusEquals(XsTimeStampClass other) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opPlusEquals(swigCPtr, this, XsTimeStampClass.getCPtr(other), other), false);
  }

  public XsTimeStampClass opSubtractEquals(XsTimeStampClass d) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opSubtractEquals(swigCPtr, this, XsTimeStampClass.getCPtr(d), d), false);
  }

  public boolean opLessThen(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opLessThen__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opLessEquals(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opLessEquals__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opEquals(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opEquals__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opGreaterThen(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opGreaterThen__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opGreaterEquals(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opGreaterEquals__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opUnequals(XsTimeStampClass other) {
    return minimalJNI.XsTimeStampClass_opUnequals__SWIG_0(swigCPtr, this, XsTimeStampClass.getCPtr(other), other);
  }

  public boolean opLessThen(int other) {
    return minimalJNI.XsTimeStampClass_opLessThen__SWIG_1(swigCPtr, this, other);
  }

  public boolean opLessEquals(int other) {
    return minimalJNI.XsTimeStampClass_opLessEquals__SWIG_1(swigCPtr, this, other);
  }

  public boolean opEquals(int other) {
    return minimalJNI.XsTimeStampClass_opEquals__SWIG_1(swigCPtr, this, other);
  }

  public boolean opGreaterThen(int other) {
    return minimalJNI.XsTimeStampClass_opGreaterThen__SWIG_1(swigCPtr, this, other);
  }

  public boolean opGreaterEquals(int other) {
    return minimalJNI.XsTimeStampClass_opGreaterEquals__SWIG_1(swigCPtr, this, other);
  }

  public boolean opUnequals(int other) {
    return minimalJNI.XsTimeStampClass_opUnequals__SWIG_1(swigCPtr, this, other);
  }

  public long secondTime() {
    return minimalJNI.XsTimeStampClass_secondTime(swigCPtr, this);
  }

  public int milliSecondPart() {
    return minimalJNI.XsTimeStampClass_milliSecondPart(swigCPtr, this);
  }

  public int secondPart() {
    return minimalJNI.XsTimeStampClass_secondPart(swigCPtr, this);
  }

  public int minutePart() {
    return minimalJNI.XsTimeStampClass_minutePart(swigCPtr, this);
  }

  public int hourPart() {
    return minimalJNI.XsTimeStampClass_hourPart(swigCPtr, this);
  }

  public static XsTimeStampClass now() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_now(), true);
  }

  public static long nowMs() {
    return minimalJNI.XsTimeStampClass_nowMs();
  }

  public long elapsedToNow() {
    return minimalJNI.XsTimeStampClass_elapsedToNow(swigCPtr, this);
  }

  public static XsTimeStampClass maxValue() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_maxValue(), true);
  }

  public XsTimeStampClass opIncrement() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opIncrement__SWIG_0(swigCPtr, this), false);
  }

  public XsTimeStampClass opIncrement(int arg0) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opIncrement__SWIG_1(swigCPtr, this, arg0), true);
  }

  public XsTimeStampClass opDecrement() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opDecrement__SWIG_0(swigCPtr, this), false);
  }

  public XsTimeStampClass opDecrement(int arg0) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_opDecrement__SWIG_1(swigCPtr, this, arg0), true);
  }

  public XsTimeStampClass utcToLocalTime() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_utcToLocalTime__SWIG_0(swigCPtr, this), true);
  }

  public XsTimeStampClass localToUtcTime() {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_localToUtcTime__SWIG_0(swigCPtr, this), true);
  }

  public XsTimeStampClass utcToLocalTime(XsTimeInfo info) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_utcToLocalTime__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeStampClass localToUtcTime(XsTimeInfo info) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_localToUtcTime__SWIG_1(swigCPtr, this, XsTimeInfo.getCPtr(info), info), true);
  }

  public XsTimeStampClass utcToLocalTime(long utcOffset) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_utcToLocalTime__SWIG_2(swigCPtr, this, utcOffset), true);
  }

  public XsTimeStampClass localToUtcTime(long utcOffset) {
    return new XsTimeStampClass(minimalJNI.XsTimeStampClass_localToUtcTime__SWIG_2(swigCPtr, this, utcOffset), true);
  }

}
