/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class CallbackHandler extends XsCallback {
  private transient long swigCPtr;

  protected CallbackHandler(long cPtr, boolean cMemoryOwn) {
    super(minimalJNI.CallbackHandler_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CallbackHandler obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_CallbackHandler(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public CallbackHandler(long maxBufferSize) {
    this(minimalJNI.new_CallbackHandler__SWIG_0(maxBufferSize), true);
  }

  public CallbackHandler() {
    this(minimalJNI.new_CallbackHandler__SWIG_1(), true);
  }

  public boolean packetAvailable() {
    return minimalJNI.CallbackHandler_packetAvailable(swigCPtr, this);
  }

  public XsDataPacketClass getNextPacket() {
    return new XsDataPacketClass(minimalJNI.CallbackHandler_getNextPacket(swigCPtr, this), true);
  }

}
