/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class int24_t {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected int24_t(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(int24_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_int24_t(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_vals(SWIGTYPE_p_unsigned_char value) {
    minimalJNI.int24_t_m_vals_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getM_vals() {
    long cPtr = minimalJNI.int24_t_m_vals_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public double toDouble() {
    return minimalJNI.int24_t_toDouble(swigCPtr, this);
  }

  public int24_t() {
    this(minimalJNI.new_int24_t(), true);
  }

}
