/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class MidReplyObject extends ReplyObject {
  private transient long swigCPtr;

  protected MidReplyObject(long cPtr, boolean cMemoryOwn) {
    super(minimalJNI.MidReplyObject_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(MidReplyObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_MidReplyObject(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public MidReplyObject(short messageId) {
    this(minimalJNI.new_MidReplyObject(messageId), true);
  }

  public boolean isReplyFor(XsMessageClass message) {
    return minimalJNI.MidReplyObject_isReplyFor(swigCPtr, this, XsMessageClass.getCPtr(message), message);
  }

  public short msgId() {
    return minimalJNI.MidReplyObject_msgId(swigCPtr, this);
  }

}
