/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public interface minimalConstants {
  public final static int XS_PREAMBLE = minimalJNI.XS_PREAMBLE_get();
  public final static int XS_EXTLENCODE = minimalJNI.XS_EXTLENCODE_get();
  public final static int XS_LEN_MSGHEADER = minimalJNI.XS_LEN_MSGHEADER_get();
  public final static int XS_LEN_MSGEXTHEADER = minimalJNI.XS_LEN_MSGEXTHEADER_get();
  public final static int XS_LEN_MSGHEADERCS = minimalJNI.XS_LEN_MSGHEADERCS_get();
  public final static int XS_LEN_MSGEXTHEADERCS = minimalJNI.XS_LEN_MSGEXTHEADERCS_get();
  public final static int XS_LEN_CHECKSUM = minimalJNI.XS_LEN_CHECKSUM_get();
  public final static int XS_LEN_UNSIGSHORT = minimalJNI.XS_LEN_UNSIGSHORT_get();
  public final static int XS_LEN_UNSIGINT = minimalJNI.XS_LEN_UNSIGINT_get();
  public final static int XS_LEN_FLOAT = minimalJNI.XS_LEN_FLOAT_get();
  public final static int XS_MAXDATALEN = minimalJNI.XS_MAXDATALEN_get();
  public final static int XS_MAXSHORTDATALEN = minimalJNI.XS_MAXSHORTDATALEN_get();
  public final static int XS_MAXMSGLEN = minimalJNI.XS_MAXMSGLEN_get();
  public final static int XS_MAXSHORTMSGLEN = minimalJNI.XS_MAXSHORTMSGLEN_get();
  public final static int XS_MAXGARBAGE = minimalJNI.XS_MAXGARBAGE_get();
  public final static int XSDEVICEID_PRODUCT_CODE_LEN = minimalJNI.XSDEVICEID_PRODUCT_CODE_LEN_get();
  public final static String XSDEVICEID_PRODUCT_CODE_INIT = minimalJNI.XSDEVICEID_PRODUCT_CODE_INIT_get();
  public final static int XS_MAX_FILTERPROFILES = minimalJNI.XS_MAX_FILTERPROFILES_get();
  public final static int XS_LEN_FILTERPROFILELABEL_TERM = minimalJNI.XS_LEN_FILTERPROFILELABEL_TERM_get();
  public final static int XS_LEN_FILTERPROFILEKIND_TERM = minimalJNI.XS_LEN_FILTERPROFILEKIND_TERM_get();
  public final static int XS_MAX_FILTERPROFILES_IN_MT = minimalJNI.XS_MAX_FILTERPROFILES_IN_MT_get();
  public final static int B230400 = minimalJNI.B230400_get();
  public final static int B460800 = minimalJNI.B460800_get();
  public final static int B921600 = minimalJNI.B921600_get();
  public final static int XCDI_MAX_FREQUENCY_VAL = minimalJNI.XCDI_MAX_FREQUENCY_VAL_get();
  public final static int XS_MAX_CANOUTPUTCONFIGURATIONS = minimalJNI.XS_MAX_CANOUTPUTCONFIGURATIONS_get();
  public final static int FSFL_ClipAccShift = minimalJNI.FSFL_ClipAccShift_get();
  public final static int FSFL_ClipGyrShift = minimalJNI.FSFL_ClipGyrShift_get();
  public final static int FSFL_ClipMagshift = minimalJNI.FSFL_ClipMagshift_get();
  public final static int FSFL_RotationShift = minimalJNI.FSFL_RotationShift_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_NONE = minimalJNI.GNSS_PVT_FLAGS_GNSS_FIX_NONE_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_SINGLE = minimalJNI.GNSS_PVT_FLAGS_GNSS_FIX_SINGLE_get();
  public final static int GNSS_PVT_FLAGS_GNSS_FIX_DIFFERENTIAL = minimalJNI.GNSS_PVT_FLAGS_GNSS_FIX_DIFFERENTIAL_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_NONE = minimalJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_NONE_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_FLOATING = minimalJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_FLOATING_get();
  public final static int GNSS_PVT_FLAGS_CARRIER_SOLUTION_FIXED = minimalJNI.GNSS_PVT_FLAGS_CARRIER_SOLUTION_FIXED_get();
  public final static int GNSS_ACCURACY_DEFAULT_DEVIATION = minimalJNI.GNSS_ACCURACY_DEFAULT_DEVIATION_get();
  public final static int XSENS_VENDOR_ID = minimalJNI.XSENS_VENDOR_ID_get();
  public final static int FTDI_VENDOR_ID = minimalJNI.FTDI_VENDOR_ID_get();
  public final static int XSFINGERSEGMENTCOUNT = minimalJNI.XSFINGERSEGMENTCOUNT_get();
  public final static int XS_MAX_OUTPUTCONFIGURATIONS = minimalJNI.XS_MAX_OUTPUTCONFIGURATIONS_get();
}
