/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class OpenPortStage {
  public final static OpenPortStage OPS_OpenPort = new OpenPortStage("OPS_OpenPort", minimalJNI.OPS_OpenPort_get());
  public final static OpenPortStage OPS_InitDevice = new OpenPortStage("OPS_InitDevice", minimalJNI.OPS_InitDevice_get());
  public final static OpenPortStage OPS_InitStart = new OpenPortStage("OPS_InitStart", minimalJNI.OPS_InitStart_get());
  public final static OpenPortStage OPS_Full = new OpenPortStage("OPS_Full", minimalJNI.OPS_Full_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static OpenPortStage swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + OpenPortStage.class + " with value " + swigValue);
  }

  private OpenPortStage(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private OpenPortStage(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private OpenPortStage(String swigName, OpenPortStage swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static OpenPortStage[] swigValues = { OPS_OpenPort, OPS_InitDevice, OPS_InitStart, OPS_Full };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

