/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class ReplyObject {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ReplyObject(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ReplyObject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_ReplyObject(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMessage(XsMessageClass msg) {
    minimalJNI.ReplyObject_setMessage(swigCPtr, this, XsMessageClass.getCPtr(msg), msg);
  }

  public XsMessageClass message(long timeout) {
    return new XsMessageClass(minimalJNI.ReplyObject_message(swigCPtr, this, timeout), true);
  }

  public boolean isReplyFor(XsMessageClass message) {
    return minimalJNI.ReplyObject_isReplyFor(swigCPtr, this, XsMessageClass.getCPtr(message), message);
  }

  public short msgId() {
    return minimalJNI.ReplyObject_msgId(swigCPtr, this);
  }

}
