/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class SnapshotStatusFlag {
  public final static SnapshotStatusFlag FSFL_ClipAccX = new SnapshotStatusFlag("FSFL_ClipAccX", minimalJNI.FSFL_ClipAccX_get());
  public final static SnapshotStatusFlag FSFL_ClipAccY = new SnapshotStatusFlag("FSFL_ClipAccY", minimalJNI.FSFL_ClipAccY_get());
  public final static SnapshotStatusFlag FSFL_ClipAccZ = new SnapshotStatusFlag("FSFL_ClipAccZ", minimalJNI.FSFL_ClipAccZ_get());
  public final static SnapshotStatusFlag FSFL_ClipAccMask = new SnapshotStatusFlag("FSFL_ClipAccMask", minimalJNI.FSFL_ClipAccMask_get());
  public final static SnapshotStatusFlag FSFL_ClipGyrX = new SnapshotStatusFlag("FSFL_ClipGyrX", minimalJNI.FSFL_ClipGyrX_get());
  public final static SnapshotStatusFlag FSFL_ClipGyrY = new SnapshotStatusFlag("FSFL_ClipGyrY", minimalJNI.FSFL_ClipGyrY_get());
  public final static SnapshotStatusFlag FSFL_ClipGyrZ = new SnapshotStatusFlag("FSFL_ClipGyrZ", minimalJNI.FSFL_ClipGyrZ_get());
  public final static SnapshotStatusFlag FSFL_ClipGyrMask = new SnapshotStatusFlag("FSFL_ClipGyrMask", minimalJNI.FSFL_ClipGyrMask_get());
  public final static SnapshotStatusFlag FSFL_ClipMagX = new SnapshotStatusFlag("FSFL_ClipMagX", minimalJNI.FSFL_ClipMagX_get());
  public final static SnapshotStatusFlag FSFL_ClipMagY = new SnapshotStatusFlag("FSFL_ClipMagY", minimalJNI.FSFL_ClipMagY_get());
  public final static SnapshotStatusFlag FSFL_ClipMagZ = new SnapshotStatusFlag("FSFL_ClipMagZ", minimalJNI.FSFL_ClipMagZ_get());
  public final static SnapshotStatusFlag FSFL_ClipMagMask = new SnapshotStatusFlag("FSFL_ClipMagMask", minimalJNI.FSFL_ClipMagMask_get());
  public final static SnapshotStatusFlag FSFL_MagIsNew = new SnapshotStatusFlag("FSFL_MagIsNew", minimalJNI.FSFL_MagIsNew_get());
  public final static SnapshotStatusFlag FSFL_BaroIsNew = new SnapshotStatusFlag("FSFL_BaroIsNew", minimalJNI.FSFL_BaroIsNew_get());
  public final static SnapshotStatusFlag FSFL_RotationMask = new SnapshotStatusFlag("FSFL_RotationMask", minimalJNI.FSFL_RotationMask_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SnapshotStatusFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SnapshotStatusFlag.class + " with value " + swigValue);
  }

  private SnapshotStatusFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SnapshotStatusFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SnapshotStatusFlag(String swigName, SnapshotStatusFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SnapshotStatusFlag[] swigValues = { FSFL_ClipAccX, FSFL_ClipAccY, FSFL_ClipAccZ, FSFL_ClipAccMask, FSFL_ClipGyrX, FSFL_ClipGyrY, FSFL_ClipGyrZ, FSFL_ClipGyrMask, FSFL_ClipMagX, FSFL_ClipMagY, FSFL_ClipMagZ, FSFL_ClipMagMask, FSFL_MagIsNew, FSFL_BaroIsNew, FSFL_RotationMask };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

