/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public SWIGTYPE_p_void getM_data() {
    long cPtr = minimalJNI.XsArray_m_data_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_XsSize getM_size() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsArray_m_size_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize getM_reserved() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsArray_m_reserved_get(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsSize getM_flags() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsArray_m_flags_get(swigCPtr, this), true);
  }

  public XsArrayDescriptor getM_descriptor() {
    long cPtr = minimalJNI.XsArray_m_descriptor_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsArrayDescriptor(cPtr, false);
  }

  public XsArray(XsArrayDescriptor descriptor, SWIGTYPE_p_XsSize count, SWIGTYPE_p_void src) {
    this(minimalJNI.new_XsArray__SWIG_0(XsArrayDescriptor.getCPtr(descriptor), descriptor, SWIGTYPE_p_XsSize.getCPtr(count), SWIGTYPE_p_void.getCPtr(src)), true);
  }

  public XsArray(XsArray src) {
    this(minimalJNI.new_XsArray__SWIG_1(XsArray.getCPtr(src), src), true);
  }

  public XsArray(XsArrayDescriptor descriptor, SWIGTYPE_p_void ref, SWIGTYPE_p_XsSize count, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsArray__SWIG_2(XsArrayDescriptor.getCPtr(descriptor), descriptor, SWIGTYPE_p_void.getCPtr(ref), SWIGTYPE_p_XsSize.getCPtr(count), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

  public XsArray opSet(XsArray src) {
    return new XsArray(minimalJNI.XsArray_opSet(swigCPtr, this, XsArray.getCPtr(src), src), false);
  }

}
