/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsDataPacketClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDataPacketClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDataPacketClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsDataPacketClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDataPacketClass(XsMessageClass msg) {
    this(minimalJNI.new_XsDataPacketClass__SWIG_0(XsMessageClass.getCPtr(msg), msg), true);
  }

  public XsDataPacketClass() {
    this(minimalJNI.new_XsDataPacketClass__SWIG_1(), true);
  }

  public XsDataPacketClass(XsDataPacketClass pack) {
    this(minimalJNI.new_XsDataPacketClass__SWIG_2(XsDataPacketClass.getCPtr(pack), pack), true);
  }

  public XsDataPacketClass opSet(XsDataPacketClass other) {
    return new XsDataPacketClass(minimalJNI.XsDataPacketClass_opSet(swigCPtr, this, XsDataPacketClass.getCPtr(other), other), false);
  }

  public void swap(XsDataPacketClass other) {
    minimalJNI.XsDataPacketClass_swap(swigCPtr, this, XsDataPacketClass.getCPtr(other), other);
  }

  public void clear(SWIGTYPE_p_XsDataIdentifier id) {
    minimalJNI.XsDataPacketClass_clear__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(id));
  }

  public void clear() {
    minimalJNI.XsDataPacketClass_clear__SWIG_1(swigCPtr, this);
  }

  public boolean empty() {
    return minimalJNI.XsDataPacketClass_empty(swigCPtr, this);
  }

  public XsDeviceIdClass deviceId() {
    return new XsDeviceIdClass(minimalJNI.XsDataPacketClass_deviceId(swigCPtr, this), true);
  }

  public int itemCount() {
    return minimalJNI.XsDataPacketClass_itemCount(swigCPtr, this);
  }

  public void setMessage(XsMessageClass msg) {
    minimalJNI.XsDataPacketClass_setMessage(swigCPtr, this, XsMessageClass.getCPtr(msg), msg);
  }

  public XsMessageClass toMessage() {
    return new XsMessageClass(minimalJNI.XsDataPacketClass_toMessage(swigCPtr, this), true);
  }

  public void setDeviceId(XsDeviceIdClass id) {
    minimalJNI.XsDataPacketClass_setDeviceId(swigCPtr, this, XsDeviceIdClass.getCPtr(id), id);
  }

  public SWIGTYPE_p_XsDataIdentifier dataFormat(SWIGTYPE_p_XsDataIdentifier id) {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsDataPacketClass_dataFormat(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(id)), true);
  }

  public XsUShortVector rawAcceleration() {
    return new XsUShortVector(minimalJNI.XsDataPacketClass_rawAcceleration(swigCPtr, this), true);
  }

  public XsVectorClass rawAccelerationConverted() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_rawAccelerationConverted(swigCPtr, this), true);
  }

  public boolean containsRawAcceleration() {
    return minimalJNI.XsDataPacketClass_containsRawAcceleration(swigCPtr, this);
  }

  public void setRawAcceleration(XsUShortVector vec) {
    minimalJNI.XsDataPacketClass_setRawAcceleration(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawGyroscopeData() {
    return new XsUShortVector(minimalJNI.XsDataPacketClass_rawGyroscopeData(swigCPtr, this), true);
  }

  public XsVectorClass rawGyroscopeDataConverted() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_rawGyroscopeDataConverted(swigCPtr, this), true);
  }

  public boolean containsRawGyroscopeData() {
    return minimalJNI.XsDataPacketClass_containsRawGyroscopeData(swigCPtr, this);
  }

  public void setRawGyroscopeData(XsUShortVector vec) {
    minimalJNI.XsDataPacketClass_setRawGyroscopeData(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawGyroscopeTemperatureData() {
    return new XsUShortVector(minimalJNI.XsDataPacketClass_rawGyroscopeTemperatureData(swigCPtr, this), true);
  }

  public XsVectorClass rawGyroscopeTemperatureDataConverted() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_rawGyroscopeTemperatureDataConverted(swigCPtr, this), true);
  }

  public boolean containsRawGyroscopeTemperatureData() {
    return minimalJNI.XsDataPacketClass_containsRawGyroscopeTemperatureData(swigCPtr, this);
  }

  public void setRawGyroscopeTemperatureData(XsUShortVector vec) {
    minimalJNI.XsDataPacketClass_setRawGyroscopeTemperatureData(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public XsUShortVector rawMagneticField() {
    return new XsUShortVector(minimalJNI.XsDataPacketClass_rawMagneticField(swigCPtr, this), true);
  }

  public XsVectorClass rawMagneticFieldConverted() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_rawMagneticFieldConverted(swigCPtr, this), true);
  }

  public boolean containsRawMagneticField() {
    return minimalJNI.XsDataPacketClass_containsRawMagneticField(swigCPtr, this);
  }

  public void setRawMagneticField(XsUShortVector vec) {
    minimalJNI.XsDataPacketClass_setRawMagneticField(swigCPtr, this, XsUShortVector.getCPtr(vec), vec);
  }

  public int rawTemperature() {
    return minimalJNI.XsDataPacketClass_rawTemperature(swigCPtr, this);
  }

  public boolean containsRawTemperature() {
    return minimalJNI.XsDataPacketClass_containsRawTemperature(swigCPtr, this);
  }

  public void setRawTemperature(int temp) {
    minimalJNI.XsDataPacketClass_setRawTemperature(swigCPtr, this, temp);
  }

  public XsScrData rawData() {
    return new XsScrData(minimalJNI.XsDataPacketClass_rawData(swigCPtr, this), true);
  }

  public boolean containsRawData() {
    return minimalJNI.XsDataPacketClass_containsRawData(swigCPtr, this);
  }

  public void setRawData(XsScrData data) {
    minimalJNI.XsDataPacketClass_setRawData(swigCPtr, this, XsScrData.getCPtr(data), data);
  }

  public XsVectorClass velocityIncrement() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_velocityIncrement(swigCPtr, this), true);
  }

  public boolean containsVelocityIncrement() {
    return minimalJNI.XsDataPacketClass_containsVelocityIncrement(swigCPtr, this);
  }

  public void setVelocityIncrement(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setVelocityIncrement(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsVectorClass calibratedAcceleration() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_calibratedAcceleration(swigCPtr, this), true);
  }

  public boolean containsCalibratedAcceleration() {
    return minimalJNI.XsDataPacketClass_containsCalibratedAcceleration(swigCPtr, this);
  }

  public void setCalibratedAcceleration(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setCalibratedAcceleration(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsQuaternionClass orientationIncrement() {
    return new XsQuaternionClass(minimalJNI.XsDataPacketClass_orientationIncrement(swigCPtr, this), true);
  }

  public boolean containsOrientationIncrement() {
    return minimalJNI.XsDataPacketClass_containsOrientationIncrement(swigCPtr, this);
  }

  public void setOrientationIncrement(XsQuaternionClass quat) {
    minimalJNI.XsDataPacketClass_setOrientationIncrement(swigCPtr, this, XsQuaternionClass.getCPtr(quat), quat);
  }

  public XsVectorClass calibratedGyroscopeData() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_calibratedGyroscopeData(swigCPtr, this), true);
  }

  public boolean containsCalibratedGyroscopeData() {
    return minimalJNI.XsDataPacketClass_containsCalibratedGyroscopeData(swigCPtr, this);
  }

  public void setCalibratedGyroscopeData(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setCalibratedGyroscopeData(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsVectorClass calibratedMagneticField() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_calibratedMagneticField(swigCPtr, this), true);
  }

  public boolean containsCalibratedMagneticField() {
    return minimalJNI.XsDataPacketClass_containsCalibratedMagneticField(swigCPtr, this);
  }

  public void setCalibratedMagneticField(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setCalibratedMagneticField(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsVectorClass correctedMagneticField() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_correctedMagneticField(swigCPtr, this), true);
  }

  public boolean containsCorrectedMagneticField() {
    return minimalJNI.XsDataPacketClass_containsCorrectedMagneticField(swigCPtr, this);
  }

  public void setCorrectedMagneticField(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setCorrectedMagneticField(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsCalibratedData calibratedData() {
    return new XsCalibratedData(minimalJNI.XsDataPacketClass_calibratedData(swigCPtr, this), true);
  }

  public boolean containsCalibratedData() {
    return minimalJNI.XsDataPacketClass_containsCalibratedData(swigCPtr, this);
  }

  public void setCalibratedData(XsCalibratedData data) {
    minimalJNI.XsDataPacketClass_setCalibratedData(swigCPtr, this, XsCalibratedData.getCPtr(data), data);
  }

  public XsQuaternionClass orientationQuaternion(SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    return new XsQuaternionClass(minimalJNI.XsDataPacketClass_orientationQuaternion__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem)), true);
  }

  public XsQuaternionClass orientationQuaternion() {
    return new XsQuaternionClass(minimalJNI.XsDataPacketClass_orientationQuaternion__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationQuaternion(XsQuaternionClass data, SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    minimalJNI.XsDataPacketClass_setOrientationQuaternion(swigCPtr, this, XsQuaternionClass.getCPtr(data), data, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem));
  }

  public XsEulerClass orientationEuler(SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    return new XsEulerClass(minimalJNI.XsDataPacketClass_orientationEuler__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem)), true);
  }

  public XsEulerClass orientationEuler() {
    return new XsEulerClass(minimalJNI.XsDataPacketClass_orientationEuler__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationEuler(XsEulerClass data, SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    minimalJNI.XsDataPacketClass_setOrientationEuler(swigCPtr, this, XsEulerClass.getCPtr(data), data, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem));
  }

  public XsMatrixClass orientationMatrix(SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    return new XsMatrixClass(minimalJNI.XsDataPacketClass_orientationMatrix__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem)), true);
  }

  public XsMatrixClass orientationMatrix() {
    return new XsMatrixClass(minimalJNI.XsDataPacketClass_orientationMatrix__SWIG_1(swigCPtr, this), true);
  }

  public void setOrientationMatrix(XsMatrixClass data, SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    minimalJNI.XsDataPacketClass_setOrientationMatrix(swigCPtr, this, XsMatrixClass.getCPtr(data), data, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem));
  }

  public boolean containsOrientation() {
    return minimalJNI.XsDataPacketClass_containsOrientation(swigCPtr, this);
  }

  public SWIGTYPE_p_XsDataIdentifier orientationIdentifier() {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsDataPacketClass_orientationIdentifier(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsDataIdentifier coordinateSystemOrientation() {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsDataPacketClass_coordinateSystemOrientation(swigCPtr, this), true);
  }

  public XsSdiData sdiData() {
    return new XsSdiData(minimalJNI.XsDataPacketClass_sdiData(swigCPtr, this), true);
  }

  public boolean containsSdiData() {
    return minimalJNI.XsDataPacketClass_containsSdiData(swigCPtr, this);
  }

  public void setSdiData(XsSdiData data) {
    minimalJNI.XsDataPacketClass_setSdiData(swigCPtr, this, XsSdiData.getCPtr(data), data);
  }

  public XsGloveData gloveData(XsHandId hand) {
    return new XsGloveData(minimalJNI.XsDataPacketClass_gloveData(swigCPtr, this, hand.swigValue()), true);
  }

  public boolean containsGloveData(XsHandId hand) {
    return minimalJNI.XsDataPacketClass_containsGloveData__SWIG_0(swigCPtr, this, hand.swigValue());
  }

  public boolean containsGloveData() {
    return minimalJNI.XsDataPacketClass_containsGloveData__SWIG_1(swigCPtr, this);
  }

  public void setGloveData(XsGloveData data, XsHandId hand) {
    minimalJNI.XsDataPacketClass_setGloveData(swigCPtr, this, XsGloveData.getCPtr(data), data, hand.swigValue());
  }

  public XsDeviceIdClass storedDeviceId() {
    return new XsDeviceIdClass(minimalJNI.XsDataPacketClass_storedDeviceId(swigCPtr, this), true);
  }

  public boolean containsStoredDeviceId() {
    return minimalJNI.XsDataPacketClass_containsStoredDeviceId(swigCPtr, this);
  }

  public void setStoredDeviceId(XsDeviceIdClass data) {
    minimalJNI.XsDataPacketClass_setStoredDeviceId(swigCPtr, this, XsDeviceIdClass.getCPtr(data), data);
  }

  public int storedLocationId() {
    return minimalJNI.XsDataPacketClass_storedLocationId(swigCPtr, this);
  }

  public boolean containsStoredLocationId() {
    return minimalJNI.XsDataPacketClass_containsStoredLocationId(swigCPtr, this);
  }

  public void setStoredLocationId(int data) {
    minimalJNI.XsDataPacketClass_setStoredLocationId(swigCPtr, this, data);
  }

  public long status() {
    return minimalJNI.XsDataPacketClass_status(swigCPtr, this);
  }

  public boolean containsStatus() {
    return minimalJNI.XsDataPacketClass_containsStatus(swigCPtr, this);
  }

  public boolean containsDetailedStatus() {
    return minimalJNI.XsDataPacketClass_containsDetailedStatus(swigCPtr, this);
  }

  public void setStatus(long data) {
    minimalJNI.XsDataPacketClass_setStatus(swigCPtr, this, data);
  }

  public void setStatusByte(short data) {
    minimalJNI.XsDataPacketClass_setStatusByte(swigCPtr, this, data);
  }

  public short packetCounter8() {
    return minimalJNI.XsDataPacketClass_packetCounter8(swigCPtr, this);
  }

  public boolean containsPacketCounter8() {
    return minimalJNI.XsDataPacketClass_containsPacketCounter8(swigCPtr, this);
  }

  public void setPacketCounter8(short counter) {
    minimalJNI.XsDataPacketClass_setPacketCounter8(swigCPtr, this, counter);
  }

  public int packetCounter() {
    return minimalJNI.XsDataPacketClass_packetCounter(swigCPtr, this);
  }

  public boolean containsPacketCounter() {
    return minimalJNI.XsDataPacketClass_containsPacketCounter(swigCPtr, this);
  }

  public void setPacketCounter(int counter) {
    minimalJNI.XsDataPacketClass_setPacketCounter(swigCPtr, this, counter);
  }

  public long sampleTimeFine() {
    return minimalJNI.XsDataPacketClass_sampleTimeFine(swigCPtr, this);
  }

  public boolean containsSampleTimeFine() {
    return minimalJNI.XsDataPacketClass_containsSampleTimeFine(swigCPtr, this);
  }

  public void setSampleTimeFine(long counter) {
    minimalJNI.XsDataPacketClass_setSampleTimeFine(swigCPtr, this, counter);
  }

  public long sampleTimeCoarse() {
    return minimalJNI.XsDataPacketClass_sampleTimeCoarse(swigCPtr, this);
  }

  public boolean containsSampleTimeCoarse() {
    return minimalJNI.XsDataPacketClass_containsSampleTimeCoarse(swigCPtr, this);
  }

  public void setSampleTimeCoarse(long counter) {
    minimalJNI.XsDataPacketClass_setSampleTimeCoarse(swigCPtr, this, counter);
  }

  public java.math.BigInteger sampleTime64() {
    return minimalJNI.XsDataPacketClass_sampleTime64(swigCPtr, this);
  }

  public boolean containsSampleTime64() {
    return minimalJNI.XsDataPacketClass_containsSampleTime64(swigCPtr, this);
  }

  public void setSampleTime64(java.math.BigInteger counter) {
    minimalJNI.XsDataPacketClass_setSampleTime64(swigCPtr, this, counter);
  }

  public XsVectorClass freeAcceleration() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_freeAcceleration(swigCPtr, this), true);
  }

  public boolean containsFreeAcceleration() {
    return minimalJNI.XsDataPacketClass_containsFreeAcceleration(swigCPtr, this);
  }

  public void setFreeAcceleration(XsVectorClass g) {
    minimalJNI.XsDataPacketClass_setFreeAcceleration(swigCPtr, this, XsVectorClass.getCPtr(g), g);
  }

  public double temperature() {
    return minimalJNI.XsDataPacketClass_temperature(swigCPtr, this);
  }

  public boolean containsTemperature() {
    return minimalJNI.XsDataPacketClass_containsTemperature(swigCPtr, this);
  }

  public void setTemperature(double temperature) {
    minimalJNI.XsDataPacketClass_setTemperature(swigCPtr, this, temperature);
  }

  public XsPressure pressure() {
    return new XsPressure(minimalJNI.XsDataPacketClass_pressure(swigCPtr, this), true);
  }

  public boolean containsPressure() {
    return minimalJNI.XsDataPacketClass_containsPressure(swigCPtr, this);
  }

  public boolean containsPressureAge() {
    return minimalJNI.XsDataPacketClass_containsPressureAge(swigCPtr, this);
  }

  public void setPressure(XsPressure data) {
    minimalJNI.XsDataPacketClass_setPressure(swigCPtr, this, XsPressure.getCPtr(data), data);
  }

  public XsAnalogInData analogIn1Data() {
    return new XsAnalogInData(minimalJNI.XsDataPacketClass_analogIn1Data(swigCPtr, this), true);
  }

  public boolean containsAnalogIn1Data() {
    return minimalJNI.XsDataPacketClass_containsAnalogIn1Data(swigCPtr, this);
  }

  public void setAnalogIn1Data(XsAnalogInData data) {
    minimalJNI.XsDataPacketClass_setAnalogIn1Data(swigCPtr, this, XsAnalogInData.getCPtr(data), data);
  }

  public XsAnalogInData analogIn2Data() {
    return new XsAnalogInData(minimalJNI.XsDataPacketClass_analogIn2Data(swigCPtr, this), true);
  }

  public boolean containsAnalogIn2Data() {
    return minimalJNI.XsDataPacketClass_containsAnalogIn2Data(swigCPtr, this);
  }

  public void setAnalogIn2Data(XsAnalogInData data) {
    minimalJNI.XsDataPacketClass_setAnalogIn2Data(swigCPtr, this, XsAnalogInData.getCPtr(data), data);
  }

  public XsVectorClass positionLLA() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_positionLLA(swigCPtr, this), true);
  }

  public boolean containsPositionLLA() {
    return minimalJNI.XsDataPacketClass_containsPositionLLA(swigCPtr, this);
  }

  public void setPositionLLA(XsVectorClass data) {
    minimalJNI.XsDataPacketClass_setPositionLLA(swigCPtr, this, XsVectorClass.getCPtr(data), data);
  }

  public XsVectorClass latitudeLongitude() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_latitudeLongitude(swigCPtr, this), true);
  }

  public boolean containsLatitudeLongitude() {
    return minimalJNI.XsDataPacketClass_containsLatitudeLongitude(swigCPtr, this);
  }

  public void setLatitudeLongitude(XsVectorClass data) {
    minimalJNI.XsDataPacketClass_setLatitudeLongitude(swigCPtr, this, XsVectorClass.getCPtr(data), data);
  }

  public double altitude() {
    return minimalJNI.XsDataPacketClass_altitude(swigCPtr, this);
  }

  public boolean containsAltitude() {
    return minimalJNI.XsDataPacketClass_containsAltitude(swigCPtr, this);
  }

  public void setAltitude(double data) {
    minimalJNI.XsDataPacketClass_setAltitude(swigCPtr, this, data);
  }

  public double altitudeMsl() {
    return minimalJNI.XsDataPacketClass_altitudeMsl(swigCPtr, this);
  }

  public boolean containsAltitudeMsl() {
    return minimalJNI.XsDataPacketClass_containsAltitudeMsl(swigCPtr, this);
  }

  public void setAltitudeMsl(double data) {
    minimalJNI.XsDataPacketClass_setAltitudeMsl(swigCPtr, this, data);
  }

  public XsVectorClass velocity(SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_velocity__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem)), true);
  }

  public XsVectorClass velocity() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_velocity__SWIG_1(swigCPtr, this), true);
  }

  public boolean containsVelocity() {
    return minimalJNI.XsDataPacketClass_containsVelocity(swigCPtr, this);
  }

  public void setVelocity(XsVectorClass data, SWIGTYPE_p_XsDataIdentifier coordinateSystem) {
    minimalJNI.XsDataPacketClass_setVelocity(swigCPtr, this, XsVectorClass.getCPtr(data), data, SWIGTYPE_p_XsDataIdentifier.getCPtr(coordinateSystem));
  }

  public SWIGTYPE_p_XsDataIdentifier velocityIdentifier() {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsDataPacketClass_velocityIdentifier(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsDataIdentifier coordinateSystemVelocity() {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsDataPacketClass_coordinateSystemVelocity(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsTimeInfo utcTime() {
    return new SWIGTYPE_p_XsTimeInfo(minimalJNI.XsDataPacketClass_utcTime(swigCPtr, this), true);
  }

  public boolean containsUtcTime() {
    return minimalJNI.XsDataPacketClass_containsUtcTime(swigCPtr, this);
  }

  public void setUtcTime(SWIGTYPE_p_XsTimeInfo data) {
    minimalJNI.XsDataPacketClass_setUtcTime(swigCPtr, this, SWIGTYPE_p_XsTimeInfo.getCPtr(data));
  }

  public XsRangeClass frameRange() {
    return new XsRangeClass(minimalJNI.XsDataPacketClass_frameRange(swigCPtr, this), true);
  }

  public boolean containsFrameRange() {
    return minimalJNI.XsDataPacketClass_containsFrameRange(swigCPtr, this);
  }

  public void setFrameRange(XsRangeClass r) {
    minimalJNI.XsDataPacketClass_setFrameRange(swigCPtr, this, XsRangeClass.getCPtr(r), r);
  }

  public int rssi() {
    return minimalJNI.XsDataPacketClass_rssi(swigCPtr, this);
  }

  public boolean containsRssi() {
    return minimalJNI.XsDataPacketClass_containsRssi(swigCPtr, this);
  }

  public void setRssi(int r) {
    minimalJNI.XsDataPacketClass_setRssi(swigCPtr, this, r);
  }

  public XsRawGnssPvtData rawGnssPvtData() {
    return new XsRawGnssPvtData(minimalJNI.XsDataPacketClass_rawGnssPvtData(swigCPtr, this), true);
  }

  public boolean containsRawGnssPvtData() {
    return minimalJNI.XsDataPacketClass_containsRawGnssPvtData(swigCPtr, this);
  }

  public void setRawGnssPvtData(XsRawGnssPvtData raw) {
    minimalJNI.XsDataPacketClass_setRawGnssPvtData(swigCPtr, this, XsRawGnssPvtData.getCPtr(raw), raw);
  }

  public short gnssAge() {
    return minimalJNI.XsDataPacketClass_gnssAge(swigCPtr, this);
  }

  public boolean containsGnssAge() {
    return minimalJNI.XsDataPacketClass_containsGnssAge(swigCPtr, this);
  }

  public void setGnssAge(short age) {
    minimalJNI.XsDataPacketClass_setGnssAge(swigCPtr, this, age);
  }

  public XsRawGnssSatInfo rawGnssSatInfo() {
    return new XsRawGnssSatInfo(minimalJNI.XsDataPacketClass_rawGnssSatInfo(swigCPtr, this), true);
  }

  public boolean containsRawGnssSatInfo() {
    return minimalJNI.XsDataPacketClass_containsRawGnssSatInfo(swigCPtr, this);
  }

  public void setRawGnssSatInfo(XsRawGnssSatInfo data) {
    minimalJNI.XsDataPacketClass_setRawGnssSatInfo(swigCPtr, this, XsRawGnssSatInfo.getCPtr(data), data);
  }

  public long gnssPvtPulse() {
    return minimalJNI.XsDataPacketClass_gnssPvtPulse(swigCPtr, this);
  }

  public boolean containsGnssPvtPulse() {
    return minimalJNI.XsDataPacketClass_containsGnssPvtPulse(swigCPtr, this);
  }

  public void setGnssPvtPulse(long counter) {
    minimalJNI.XsDataPacketClass_setGnssPvtPulse(swigCPtr, this, counter);
  }

  public XsSnapshot fullSnapshot() {
    return new XsSnapshot(minimalJNI.XsDataPacketClass_fullSnapshot(swigCPtr, this), true);
  }

  public boolean containsFullSnapshot() {
    return minimalJNI.XsDataPacketClass_containsFullSnapshot(swigCPtr, this);
  }

  public void setFullSnapshot(XsSnapshot data, boolean retransmission) {
    minimalJNI.XsDataPacketClass_setFullSnapshot(swigCPtr, this, XsSnapshot.getCPtr(data), data, retransmission);
  }

  public XsSnapshot awindaSnapshot() {
    return new XsSnapshot(minimalJNI.XsDataPacketClass_awindaSnapshot(swigCPtr, this), true);
  }

  public boolean containsAwindaSnapshot() {
    return minimalJNI.XsDataPacketClass_containsAwindaSnapshot(swigCPtr, this);
  }

  public void setAwindaSnapshot(XsSnapshot raw, boolean retransmission) {
    minimalJNI.XsDataPacketClass_setAwindaSnapshot(swigCPtr, this, XsSnapshot.getCPtr(raw), raw, retransmission);
  }

  public boolean isAwindaSnapshotARetransmission() {
    return minimalJNI.XsDataPacketClass_isAwindaSnapshotARetransmission(swigCPtr, this);
  }

  public XsGloveSnapshot gloveSnapshot(XsHandId hand) {
    return new XsGloveSnapshot(minimalJNI.XsDataPacketClass_gloveSnapshot(swigCPtr, this, hand.swigValue()), true);
  }

  public boolean containsGloveSnapshot(XsHandId hand) {
    return minimalJNI.XsDataPacketClass_containsGloveSnapshot__SWIG_0(swigCPtr, this, hand.swigValue());
  }

  public boolean containsGloveSnapshot() {
    return minimalJNI.XsDataPacketClass_containsGloveSnapshot__SWIG_1(swigCPtr, this);
  }

  public void setGloveSnapshot(XsGloveSnapshot data, boolean retransmission, XsHandId hand) {
    minimalJNI.XsDataPacketClass_setGloveSnapshot(swigCPtr, this, XsGloveSnapshot.getCPtr(data), data, retransmission, hand.swigValue());
  }

  public XsDataPacketClass merge(XsDataPacketClass other, boolean overwrite) {
    return new XsDataPacketClass(minimalJNI.XsDataPacketClass_merge__SWIG_0(swigCPtr, this, XsDataPacketClass.getCPtr(other), other, overwrite), false);
  }

  public XsDataPacketClass merge(XsDataPacketClass other) {
    return new XsDataPacketClass(minimalJNI.XsDataPacketClass_merge__SWIG_1(swigCPtr, this, XsDataPacketClass.getCPtr(other), other), false);
  }

  public void setTimeOfArrival(XsTimeStampClass t) {
    minimalJNI.XsDataPacketClass_setTimeOfArrival(swigCPtr, this, XsTimeStampClass.getCPtr(t), t);
  }

  public XsTimeStampClass timeOfArrival() {
    return new XsTimeStampClass(minimalJNI.XsDataPacketClass_timeOfArrival(swigCPtr, this), true);
  }

  public void setEstimatedTimeOfSampling(XsTimeStampClass t) {
    minimalJNI.XsDataPacketClass_setEstimatedTimeOfSampling(swigCPtr, this, XsTimeStampClass.getCPtr(t), t);
  }

  public XsTimeStampClass estimatedTimeOfSampling() {
    return new XsTimeStampClass(minimalJNI.XsDataPacketClass_estimatedTimeOfSampling(swigCPtr, this), true);
  }

  public void setPacketId(long t) {
    minimalJNI.XsDataPacketClass_setPacketId(swigCPtr, this, t);
  }

  public long packetId() {
    return minimalJNI.XsDataPacketClass_packetId(swigCPtr, this);
  }

  public void setTriggerIndication(SWIGTYPE_p_XsDataIdentifier triggerId, SWIGTYPE_p_XsTriggerIndicationData triggerIndicationData) {
    minimalJNI.XsDataPacketClass_setTriggerIndication(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(triggerId), SWIGTYPE_p_XsTriggerIndicationData.getCPtr(triggerIndicationData));
  }

  public boolean containsTriggerIndication(SWIGTYPE_p_XsDataIdentifier triggerId) {
    return minimalJNI.XsDataPacketClass_containsTriggerIndication(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(triggerId));
  }

  public SWIGTYPE_p_XsTriggerIndicationData triggerIndication(SWIGTYPE_p_XsDataIdentifier triggerId) {
    return new SWIGTYPE_p_XsTriggerIndicationData(minimalJNI.XsDataPacketClass_triggerIndication(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(triggerId)), true);
  }

  public SWIGTYPE_p_XsByteArray rawBlob() {
    return new SWIGTYPE_p_XsByteArray(minimalJNI.XsDataPacketClass_rawBlob(swigCPtr, this), true);
  }

  public boolean containsRawBlob() {
    return minimalJNI.XsDataPacketClass_containsRawBlob(swigCPtr, this);
  }

  public void setRawBlob(SWIGTYPE_p_XsByteArray data) {
    minimalJNI.XsDataPacketClass_setRawBlob(swigCPtr, this, SWIGTYPE_p_XsByteArray.getCPtr(data));
  }

  public XsVectorClass accelerationHR() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_accelerationHR(swigCPtr, this), true);
  }

  public boolean containsAccelerationHR() {
    return minimalJNI.XsDataPacketClass_containsAccelerationHR(swigCPtr, this);
  }

  public void setAccelerationHR(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setAccelerationHR(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public XsVectorClass rateOfTurnHR() {
    return new XsVectorClass(minimalJNI.XsDataPacketClass_rateOfTurnHR(swigCPtr, this), true);
  }

  public boolean containsRateOfTurnHR() {
    return minimalJNI.XsDataPacketClass_containsRateOfTurnHR(swigCPtr, this);
  }

  public void setRateOfTurnHR(XsVectorClass vec) {
    minimalJNI.XsDataPacketClass_setRateOfTurnHR(swigCPtr, this, XsVectorClass.getCPtr(vec), vec);
  }

  public SWIGTYPE_p_std__mapT_XsDataIdentifier_void_p_t simplifiedContents() {
    return new SWIGTYPE_p_std__mapT_XsDataIdentifier_void_p_t(minimalJNI.XsDataPacketClass_simplifiedContents(swigCPtr, this), true);
  }

  public void setD(SWIGTYPE_p_DataPacketPrivate value) {
    minimalJNI.XsDataPacketClass_d_set(swigCPtr, this, SWIGTYPE_p_DataPacketPrivate.getCPtr(value));
  }

  public SWIGTYPE_p_DataPacketPrivate getD() {
    long cPtr = minimalJNI.XsDataPacketClass_d_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_DataPacketPrivate(cPtr, false);
  }

  public void setM_deviceId(XsDeviceIdClass value) {
    minimalJNI.XsDataPacketClass_m_deviceId_set(swigCPtr, this, XsDeviceIdClass.getCPtr(value), value);
  }

  public XsDeviceIdClass getM_deviceId() {
    long cPtr = minimalJNI.XsDataPacketClass_m_deviceId_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsDeviceIdClass(cPtr, false);
  }

  public void setM_toa(XsTimeStampClass value) {
    minimalJNI.XsDataPacketClass_m_toa_set(swigCPtr, this, XsTimeStampClass.getCPtr(value), value);
  }

  public XsTimeStampClass getM_toa() {
    long cPtr = minimalJNI.XsDataPacketClass_m_toa_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsTimeStampClass(cPtr, false);
  }

  public void setM_packetId(long value) {
    minimalJNI.XsDataPacketClass_m_packetId_set(swigCPtr, this, value);
  }

  public long getM_packetId() {
    return minimalJNI.XsDataPacketClass_m_packetId_get(swigCPtr, this);
  }

  public void setM_etos(XsTimeStampClass value) {
    minimalJNI.XsDataPacketClass_m_etos_set(swigCPtr, this, XsTimeStampClass.getCPtr(value), value);
  }

  public XsTimeStampClass getM_etos() {
    long cPtr = minimalJNI.XsDataPacketClass_m_etos_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsTimeStampClass(cPtr, false);
  }

}
