/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsDeviceIdArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDeviceIdArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDeviceIdArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsDeviceIdArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDeviceIdArray(SWIGTYPE_p_XsSize count, XsDeviceIdClass src) {
    this(minimalJNI.new_XsDeviceIdArray__SWIG_0(SWIGTYPE_p_XsSize.getCPtr(count), XsDeviceIdClass.getCPtr(src), src), true);
  }

  public XsDeviceIdArray(SWIGTYPE_p_XsSize count) {
    this(minimalJNI.new_XsDeviceIdArray__SWIG_1(SWIGTYPE_p_XsSize.getCPtr(count)), true);
  }

  public XsDeviceIdArray() {
    this(minimalJNI.new_XsDeviceIdArray__SWIG_2(), true);
  }

  public XsDeviceIdArray(XsDeviceIdArray other) {
    this(minimalJNI.new_XsDeviceIdArray__SWIG_3(XsDeviceIdArray.getCPtr(other), other), true);
  }

  public XsDeviceIdArray(XsDeviceIdClass ref, SWIGTYPE_p_XsSize sz, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsDeviceIdArray__SWIG_4(XsDeviceIdClass.getCPtr(ref), ref, SWIGTYPE_p_XsSize.getCPtr(sz), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

  public void clear() {
    minimalJNI.XsDeviceIdArray_clear(swigCPtr, this);
  }

  public boolean opEquals(XsDeviceIdArray other) {
    return minimalJNI.XsDeviceIdArray_opEquals(swigCPtr, this, XsDeviceIdArray.getCPtr(other), other);
  }

  public boolean opUnequals(XsDeviceIdArray other) {
    return minimalJNI.XsDeviceIdArray_opUnequals(swigCPtr, this, XsDeviceIdArray.getCPtr(other), other);
  }

  public void reserve(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_reserve(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public SWIGTYPE_p_XsSize reserved() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsDeviceIdArray_reserved(swigCPtr, this), true);
  }

  public XsArrayDescriptor descriptor() {
    return new XsArrayDescriptor(minimalJNI.XsDeviceIdArray_descriptor(swigCPtr, this), false);
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t begin() {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t(minimalJNI.XsDeviceIdArray_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t end() {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t(minimalJNI.XsDeviceIdArray_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t rbegin() {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t(minimalJNI.XsDeviceIdArray_rbegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t rend() {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t(minimalJNI.XsDeviceIdArray_rend(swigCPtr, this), true);
  }

  public XsDeviceIdClass opSquareBracket(int index) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdArray_opSquareBracket(swigCPtr, this, index), false);
  }

  public XsDeviceIdClass value(SWIGTYPE_p_XsSize index) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdArray_value(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index)), true);
  }

  public XsDeviceIdClass first() {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdArray_first(swigCPtr, this), true);
  }

  public XsDeviceIdClass last() {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdArray_last(swigCPtr, this), true);
  }

  public XsDeviceIdClass at(SWIGTYPE_p_XsSize index) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdArray_at(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index)), false);
  }

  public void insert(XsDeviceIdClass item, SWIGTYPE_p_XsSize index) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_0(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item, SWIGTYPE_p_XsSize.getCPtr(index));
  }

  public void insert(XsDeviceIdClass items, SWIGTYPE_p_XsSize index, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_1(swigCPtr, this, XsDeviceIdClass.getCPtr(items), items, SWIGTYPE_p_XsSize.getCPtr(index), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void insert(XsDeviceIdClass item, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t it) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_2(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t.getCPtr(it));
  }

  public void insert(XsDeviceIdClass item, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t it) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_3(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t.getCPtr(it));
  }

  public void insert(XsDeviceIdClass items, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t it, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_4(swigCPtr, this, XsDeviceIdClass.getCPtr(items), items, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT_1_t.getCPtr(it), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void insert(XsDeviceIdClass items, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t it, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_insert__SWIG_5(swigCPtr, this, XsDeviceIdClass.getCPtr(items), items, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplConstT__1_t.getCPtr(it), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void push_back(XsDeviceIdClass item) {
    minimalJNI.XsDeviceIdArray_push_back(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item);
  }

  public void pop_back(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_pop_back__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void pop_back() {
    minimalJNI.XsDeviceIdArray_pop_back__SWIG_1(swigCPtr, this);
  }

  public void push_front(XsDeviceIdClass item) {
    minimalJNI.XsDeviceIdArray_push_front(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item);
  }

  public void pop_front(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_pop_front__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void pop_front() {
    minimalJNI.XsDeviceIdArray_pop_front__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_XsSize size() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsDeviceIdArray_size(swigCPtr, this), true);
  }

  public void erase(SWIGTYPE_p_XsSize index, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_erase__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void erase(SWIGTYPE_p_XsSize index) {
    minimalJNI.XsDeviceIdArray_erase__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index));
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT_1_t erase(SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT_1_t it) {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT_1_t(minimalJNI.XsDeviceIdArray_erase__SWIG_2(swigCPtr, this, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT_1_t.getCPtr(it)), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT__1_t erase(SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT__1_t it) {
    return new SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT__1_t(minimalJNI.XsDeviceIdArray_erase__SWIG_3(swigCPtr, this, SWIGTYPE_p_XsArrayImplT_XsDeviceId_g_xsDeviceIdArrayDescriptor_XsDeviceIdArray_t__IteratorImplT__1_t.getCPtr(it)), true);
  }

  public void assign(SWIGTYPE_p_XsSize count, XsDeviceIdClass src) {
    minimalJNI.XsDeviceIdArray_assign(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count), XsDeviceIdClass.getCPtr(src), src);
  }

  public void resize(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_resize(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void setSize(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsDeviceIdArray_setSize(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void append(XsDeviceIdArray other) {
    minimalJNI.XsDeviceIdArray_append(swigCPtr, this, XsDeviceIdArray.getCPtr(other), other);
  }

  public XsDeviceIdArray opSet(XsDeviceIdArray other) {
    return new XsDeviceIdArray(minimalJNI.XsDeviceIdArray_opSet(swigCPtr, this, XsDeviceIdArray.getCPtr(other), other), false);
  }

  public boolean empty() {
    return minimalJNI.XsDeviceIdArray_empty(swigCPtr, this);
  }

  public SWIGTYPE_p_XsDeviceIdArray inherited() {
    return new SWIGTYPE_p_XsDeviceIdArray(minimalJNI.XsDeviceIdArray_inherited(swigCPtr, this), false);
  }

  public void swap(XsDeviceIdArray other) {
    minimalJNI.XsDeviceIdArray_swap__SWIG_0(swigCPtr, this, XsDeviceIdArray.getCPtr(other), other);
  }

  public void swap(SWIGTYPE_p_XsSize a, SWIGTYPE_p_XsSize b) {
    minimalJNI.XsDeviceIdArray_swap__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(a), SWIGTYPE_p_XsSize.getCPtr(b));
  }

  public SWIGTYPE_p_XsDeviceIdArray opLeftShift(XsDeviceIdClass item) {
    return new SWIGTYPE_p_XsDeviceIdArray(minimalJNI.XsDeviceIdArray_opLeftShift(swigCPtr, this, XsDeviceIdClass.getCPtr(item), item), false);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsDeviceIdClass needle) {
    return new SWIGTYPE_p_ptrdiff_t(minimalJNI.XsDeviceIdArray_find(swigCPtr, this, XsDeviceIdClass.getCPtr(needle), needle), true);
  }

  public void removeDuplicates() {
    minimalJNI.XsDeviceIdArray_removeDuplicates(swigCPtr, this);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    minimalJNI.XsDeviceIdArray_removeDuplicatesPredicate(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    minimalJNI.XsDeviceIdArray_sort(swigCPtr, this);
  }

  public void reverse() {
    minimalJNI.XsDeviceIdArray_reverse(swigCPtr, this);
  }

}
