/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsDeviceParameter {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDeviceParameter(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDeviceParameter obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsDeviceParameter(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDeviceParameter(XsDeviceParameterIdentifier id) {
    this(minimalJNI.new_XsDeviceParameter__SWIG_0(id.swigValue()), true);
  }

  public XsDeviceParameter(XsDeviceParameterIdentifier id, int value) {
    this(minimalJNI.new_XsDeviceParameter__SWIG_1(id.swigValue(), value), true);
  }

  public XsDeviceParameterIdentifier id() {
    return XsDeviceParameterIdentifier.swigToEnum(minimalJNI.XsDeviceParameter_id(swigCPtr, this));
  }

}
