/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsDeviceIdClass {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsDeviceIdClass(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsDeviceIdClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsDeviceIdClass(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsDeviceIdClass(String productCode, int hardwareVersion, long productVariant, java.math.BigInteger serialNumber, int subDevice) {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_0(productCode, hardwareVersion, productVariant, serialNumber, subDevice), true);
  }

  public XsDeviceIdClass(String productCode, int hardwareVersion, long productVariant, java.math.BigInteger serialNumber) {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_1(productCode, hardwareVersion, productVariant, serialNumber), true);
  }

  public XsDeviceIdClass(java.math.BigInteger serialNumber) {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_2(serialNumber), true);
  }

  public XsDeviceIdClass() {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_3(), true);
  }

  public XsDeviceIdClass(XsDeviceIdClass parent, int subDevice) {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_4(XsDeviceIdClass.getCPtr(parent), parent, subDevice), true);
  }

  public XsDeviceIdClass(XsDeviceIdClass other) {
    this(minimalJNI.new_XsDeviceIdClass__SWIG_5(XsDeviceIdClass.getCPtr(other), other), true);
  }

  public XsDeviceIdClass opSet(XsDeviceIdClass other) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_opSet(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other), false);
  }

  public static java.math.BigInteger legacyBit() {
    return minimalJNI.XsDeviceIdClass_legacyBit();
  }

  public boolean isLegacyDeviceId() {
    return minimalJNI.XsDeviceIdClass_isLegacyDeviceId(swigCPtr, this);
  }

  public java.math.BigInteger toInt() {
    return minimalJNI.XsDeviceIdClass_toInt(swigCPtr, this);
  }

  public XsStringClass productCode() {
    return new XsStringClass(minimalJNI.XsDeviceIdClass_productCode(swigCPtr, this), true);
  }

  public long productVariant() {
    return minimalJNI.XsDeviceIdClass_productVariant(swigCPtr, this);
  }

  public int hardwareVersion() {
    return minimalJNI.XsDeviceIdClass_hardwareVersion(swigCPtr, this);
  }

  public int subDevice() {
    return minimalJNI.XsDeviceIdClass_subDevice(swigCPtr, this);
  }

  public long legacyDeviceId() {
    return minimalJNI.XsDeviceIdClass_legacyDeviceId(swigCPtr, this);
  }

  public boolean isMtiX() {
    return minimalJNI.XsDeviceIdClass_isMtiX(swigCPtr, this);
  }

  public boolean isMtiX0() {
    return minimalJNI.XsDeviceIdClass_isMtiX0(swigCPtr, this);
  }

  public boolean isMtiX00() {
    return minimalJNI.XsDeviceIdClass_isMtiX00(swigCPtr, this);
  }

  public boolean isMtigX00() {
    return minimalJNI.XsDeviceIdClass_isMtigX00(swigCPtr, this);
  }

  public boolean isMtigX10() {
    return minimalJNI.XsDeviceIdClass_isMtigX10(swigCPtr, this);
  }

  public boolean isMti3X0() {
    return minimalJNI.XsDeviceIdClass_isMti3X0(swigCPtr, this);
  }

  public boolean isMti6X0() {
    return minimalJNI.XsDeviceIdClass_isMti6X0(swigCPtr, this);
  }

  public boolean isMti8X0() {
    return minimalJNI.XsDeviceIdClass_isMti8X0(swigCPtr, this);
  }

  public boolean isGlove() {
    return minimalJNI.XsDeviceIdClass_isGlove(swigCPtr, this);
  }

  public XsHandId side() {
    return XsHandId.swigToEnum(minimalJNI.XsDeviceIdClass_side(swigCPtr, this));
  }

  public boolean isDot() {
    return minimalJNI.XsDeviceIdClass_isDot(swigCPtr, this);
  }

  public boolean isRugged() {
    return minimalJNI.XsDeviceIdClass_isRugged(swigCPtr, this);
  }

  public boolean isMtw() {
    return minimalJNI.XsDeviceIdClass_isMtw(swigCPtr, this);
  }

  public boolean isMtw2() {
    return minimalJNI.XsDeviceIdClass_isMtw2(swigCPtr, this);
  }

  public boolean isMtx() {
    return minimalJNI.XsDeviceIdClass_isMtx(swigCPtr, this);
  }

  public boolean isMtx2() {
    return minimalJNI.XsDeviceIdClass_isMtx2(swigCPtr, this);
  }

  public boolean isBodyPack() {
    return minimalJNI.XsDeviceIdClass_isBodyPack(swigCPtr, this);
  }

  public boolean isBodyPackV1() {
    return minimalJNI.XsDeviceIdClass_isBodyPackV1(swigCPtr, this);
  }

  public boolean isBodyPackV2() {
    return minimalJNI.XsDeviceIdClass_isBodyPackV2(swigCPtr, this);
  }

  public boolean isWirelessMaster() {
    return minimalJNI.XsDeviceIdClass_isWirelessMaster(swigCPtr, this);
  }

  public boolean isAwindaX() {
    return minimalJNI.XsDeviceIdClass_isAwindaX(swigCPtr, this);
  }

  public boolean isAwindaXStation() {
    return minimalJNI.XsDeviceIdClass_isAwindaXStation(swigCPtr, this);
  }

  public boolean isAwindaXDongle() {
    return minimalJNI.XsDeviceIdClass_isAwindaXDongle(swigCPtr, this);
  }

  public boolean isAwindaXOem() {
    return minimalJNI.XsDeviceIdClass_isAwindaXOem(swigCPtr, this);
  }

  public boolean isAwinda2() {
    return minimalJNI.XsDeviceIdClass_isAwinda2(swigCPtr, this);
  }

  public boolean isAwinda2Station() {
    return minimalJNI.XsDeviceIdClass_isAwinda2Station(swigCPtr, this);
  }

  public boolean isAwinda2Dongle() {
    return minimalJNI.XsDeviceIdClass_isAwinda2Dongle(swigCPtr, this);
  }

  public boolean isAwinda2Oem() {
    return minimalJNI.XsDeviceIdClass_isAwinda2Oem(swigCPtr, this);
  }

  public boolean isSyncStationX() {
    return minimalJNI.XsDeviceIdClass_isSyncStationX(swigCPtr, this);
  }

  public boolean isSyncStation2() {
    return minimalJNI.XsDeviceIdClass_isSyncStation2(swigCPtr, this);
  }

  public boolean isHilDevice() {
    return minimalJNI.XsDeviceIdClass_isHilDevice(swigCPtr, this);
  }

  public boolean isImu() {
    return minimalJNI.XsDeviceIdClass_isImu(swigCPtr, this);
  }

  public boolean isVru() {
    return minimalJNI.XsDeviceIdClass_isVru(swigCPtr, this);
  }

  public boolean isAhrs() {
    return minimalJNI.XsDeviceIdClass_isAhrs(swigCPtr, this);
  }

  public boolean isGnss() {
    return minimalJNI.XsDeviceIdClass_isGnss(swigCPtr, this);
  }

  public boolean isRtk() {
    return minimalJNI.XsDeviceIdClass_isRtk(swigCPtr, this);
  }

  public boolean hasInternalGnss() {
    return minimalJNI.XsDeviceIdClass_hasInternalGnss(swigCPtr, this);
  }

  public boolean isContainerDevice() {
    return minimalJNI.XsDeviceIdClass_isContainerDevice(swigCPtr, this);
  }

  public boolean isMt() {
    return minimalJNI.XsDeviceIdClass_isMt(swigCPtr, this);
  }

  public boolean isMti() {
    return minimalJNI.XsDeviceIdClass_isMti(swigCPtr, this);
  }

  public boolean isMtig() {
    return minimalJNI.XsDeviceIdClass_isMtig(swigCPtr, this);
  }

  public boolean isMtMark4() {
    return minimalJNI.XsDeviceIdClass_isMtMark4(swigCPtr, this);
  }

  public boolean isMtMark5() {
    return minimalJNI.XsDeviceIdClass_isMtMark5(swigCPtr, this);
  }

  public XsStringClass toString() {
    return new XsStringClass(minimalJNI.XsDeviceIdClass_toString(swigCPtr, this), true);
  }

  public void fromString(XsStringClass str) {
    minimalJNI.XsDeviceIdClass_fromString(swigCPtr, this, XsStringClass.getCPtr(str), str);
  }

  public XsStringClass toDeviceTypeString(boolean makeType) {
    return new XsStringClass(minimalJNI.XsDeviceIdClass_toDeviceTypeString__SWIG_0(swigCPtr, this, makeType), true);
  }

  public XsStringClass toDeviceTypeString() {
    return new XsStringClass(minimalJNI.XsDeviceIdClass_toDeviceTypeString__SWIG_1(swigCPtr, this), true);
  }

  public void fromDeviceTypeString(XsStringClass str) {
    minimalJNI.XsDeviceIdClass_fromDeviceTypeString(swigCPtr, this, XsStringClass.getCPtr(str), str);
  }

  public boolean isValid() {
    return minimalJNI.XsDeviceIdClass_isValid(swigCPtr, this);
  }

  public boolean contains(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_contains(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean isType() {
    return minimalJNI.XsDeviceIdClass_isType(swigCPtr, this);
  }

  public XsStringClass typeName() {
    return new XsStringClass(minimalJNI.XsDeviceIdClass_typeName(swigCPtr, this), true);
  }

  public XsDeviceIdClass type() {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_type(swigCPtr, this), true);
  }

  public XsDeviceIdClass deviceType(boolean detailed) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_deviceType__SWIG_0(swigCPtr, this, detailed), true);
  }

  public XsDeviceIdClass deviceType() {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_deviceType__SWIG_1(swigCPtr, this), true);
  }

  public XsDeviceIdClass deviceTypeMask(boolean detailed) {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_deviceTypeMask__SWIG_0(swigCPtr, this, detailed), true);
  }

  public XsDeviceIdClass deviceTypeMask() {
    return new XsDeviceIdClass(minimalJNI.XsDeviceIdClass_deviceTypeMask__SWIG_1(swigCPtr, this), true);
  }

  public boolean opEquals(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opEquals(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean opUnequals(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opUnequals(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean opLessThen(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opLessThen(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean opLessEquals(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opLessEquals(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean opGreaterThen(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opGreaterThen(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean opGreaterEquals(XsDeviceIdClass other) {
    return minimalJNI.XsDeviceIdClass_opGreaterEquals(swigCPtr, this, XsDeviceIdClass.getCPtr(other), other);
  }

  public boolean isMtMk4() {
    return minimalJNI.XsDeviceIdClass_isMtMk4(swigCPtr, this);
  }

  public boolean isMtMk4_X() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_X(swigCPtr, this);
  }

  public boolean isMtMk4_1() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_1(swigCPtr, this);
  }

  public boolean isMtMk4_2() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_2(swigCPtr, this);
  }

  public boolean isMtMk4_3() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_3(swigCPtr, this);
  }

  public boolean isMtMk4_7() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_7(swigCPtr, this);
  }

  public boolean isMtMk4_X0() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_X0(swigCPtr, this);
  }

  public boolean isMtMk4_10() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_10(swigCPtr, this);
  }

  public boolean isMtMk4_20() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_20(swigCPtr, this);
  }

  public boolean isMtMk4_30() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_30(swigCPtr, this);
  }

  public boolean isMtMk4_X00() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_X00(swigCPtr, this);
  }

  public boolean isMtMk4_100() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_100(swigCPtr, this);
  }

  public boolean isMtMk4_200() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_200(swigCPtr, this);
  }

  public boolean isMtMk4_300() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_300(swigCPtr, this);
  }

  public boolean isMtMk4_400() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_400(swigCPtr, this);
  }

  public boolean isMtMk4_500() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_500(swigCPtr, this);
  }

  public boolean isMtMk4_600() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_600(swigCPtr, this);
  }

  public boolean isMtMk4_700() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_700(swigCPtr, this);
  }

  public boolean isMtMk4_710() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_710(swigCPtr, this);
  }

  public boolean isMtMk4_800() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_800(swigCPtr, this);
  }

  public boolean isMtMk4_900() {
    return minimalJNI.XsDeviceIdClass_isMtMk4_900(swigCPtr, this);
  }

  public boolean isMtMk5() {
    return minimalJNI.XsDeviceIdClass_isMtMk5(swigCPtr, this);
  }

  public boolean isMtMk5_X0() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_X0(swigCPtr, this);
  }

  public boolean isMtMk5_10() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_10(swigCPtr, this);
  }

  public boolean isMtMk5_20() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_20(swigCPtr, this);
  }

  public boolean isMtMk5_30() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_30(swigCPtr, this);
  }

  public boolean isMtMk5_X00() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_X00(swigCPtr, this);
  }

  public boolean isMtMk5_100() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_100(swigCPtr, this);
  }

  public boolean isMtMk5_200() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_200(swigCPtr, this);
  }

  public boolean isMtMk5_300() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_300(swigCPtr, this);
  }

  public boolean isMtMk5_710() {
    return minimalJNI.XsDeviceIdClass_isMtMk5_710(swigCPtr, this);
  }

}
