/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsErrorMode {
  public final static XsErrorMode XEM_Ignore = new XsErrorMode("XEM_Ignore", minimalJNI.XEM_Ignore_get());
  public final static XsErrorMode XEM_IncreasePacketCounter = new XsErrorMode("XEM_IncreasePacketCounter", minimalJNI.XEM_IncreasePacketCounter_get());
  public final static XsErrorMode XEM_IncreasePacketCounterAndSendError = new XsErrorMode("XEM_IncreasePacketCounterAndSendError", minimalJNI.XEM_IncreasePacketCounterAndSendError_get());
  public final static XsErrorMode XEM_SendErrorAndGoToConfig = new XsErrorMode("XEM_SendErrorAndGoToConfig", minimalJNI.XEM_SendErrorAndGoToConfig_get());
  public final static XsErrorMode XEM_Invalid = new XsErrorMode("XEM_Invalid");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsErrorMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsErrorMode.class + " with value " + swigValue);
  }

  private XsErrorMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsErrorMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsErrorMode(String swigName, XsErrorMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsErrorMode[] swigValues = { XEM_Ignore, XEM_IncreasePacketCounter, XEM_IncreasePacketCounterAndSendError, XEM_SendErrorAndGoToConfig, XEM_Invalid };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

