/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsFingerSnapshot {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsFingerSnapshot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsFingerSnapshot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsFingerSnapshot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_iQ(int24_t value) {
    minimalJNI.XsFingerSnapshot_m_iQ_set(swigCPtr, this, int24_t.getCPtr(value), value);
  }

  public int24_t getM_iQ() {
    long cPtr = minimalJNI.XsFingerSnapshot_m_iQ_get(swigCPtr, this);
    return (cPtr == 0) ? null : new int24_t(cPtr, false);
  }

  public void setM_iV(SWIGTYPE_p_int value) {
    minimalJNI.XsFingerSnapshot_m_iV_set(swigCPtr, this, SWIGTYPE_p_int.getCPtr(value));
  }

  public SWIGTYPE_p_int getM_iV() {
    long cPtr = minimalJNI.XsFingerSnapshot_m_iV_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_int(cPtr, false);
  }

  public void setM_mag(SWIGTYPE_p_short value) {
    minimalJNI.XsFingerSnapshot_m_mag_set(swigCPtr, this, SWIGTYPE_p_short.getCPtr(value));
  }

  public SWIGTYPE_p_short getM_mag() {
    long cPtr = minimalJNI.XsFingerSnapshot_m_mag_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public void setM_flags(int value) {
    minimalJNI.XsFingerSnapshot_m_flags_set(swigCPtr, this, value);
  }

  public int getM_flags() {
    return minimalJNI.XsFingerSnapshot_m_flags_get(swigCPtr, this);
  }

  public void setM_accClippingCounter(short value) {
    minimalJNI.XsFingerSnapshot_m_accClippingCounter_set(swigCPtr, this, value);
  }

  public short getM_accClippingCounter() {
    return minimalJNI.XsFingerSnapshot_m_accClippingCounter_get(swigCPtr, this);
  }

  public void setM_gyrClippingCounter(short value) {
    minimalJNI.XsFingerSnapshot_m_gyrClippingCounter_set(swigCPtr, this, value);
  }

  public short getM_gyrClippingCounter() {
    return minimalJNI.XsFingerSnapshot_m_gyrClippingCounter_get(swigCPtr, this);
  }

  public XsFingerSnapshot() {
    this(minimalJNI.new_XsFingerSnapshot(), true);
  }

}
