/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsGloveSnapshot {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsGloveSnapshot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsGloveSnapshot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsGloveSnapshot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_frameNumber(long value) {
    minimalJNI.XsGloveSnapshot_m_frameNumber_set(swigCPtr, this, value);
  }

  public long getM_frameNumber() {
    return minimalJNI.XsGloveSnapshot_m_frameNumber_get(swigCPtr, this);
  }

  public void setM_validSampleFlags(int value) {
    minimalJNI.XsGloveSnapshot_m_validSampleFlags_set(swigCPtr, this, value);
  }

  public int getM_validSampleFlags() {
    return minimalJNI.XsGloveSnapshot_m_validSampleFlags_get(swigCPtr, this);
  }

  public void setM_padByte(short value) {
    minimalJNI.XsGloveSnapshot_m_padByte_set(swigCPtr, this, value);
  }

  public short getM_padByte() {
    return minimalJNI.XsGloveSnapshot_m_padByte_get(swigCPtr, this);
  }

  public void setM_fingers(XsFingerSnapshot value) {
    minimalJNI.XsGloveSnapshot_m_fingers_set(swigCPtr, this, XsFingerSnapshot.getCPtr(value), value);
  }

  public XsFingerSnapshot getM_fingers() {
    long cPtr = minimalJNI.XsGloveSnapshot_m_fingers_get(swigCPtr, this);
    return (cPtr == 0) ? null : new XsFingerSnapshot(cPtr, false);
  }

  public XsGloveSnapshot() {
    this(minimalJNI.new_XsGloveSnapshot(), true);
  }

}
