/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsGnssPlatform {
  public final static XsGnssPlatform XGP_Portable = new XsGnssPlatform("XGP_Portable", minimalJNI.XGP_Portable_get());
  public final static XsGnssPlatform XGP_Stationary = new XsGnssPlatform("XGP_Stationary", minimalJNI.XGP_Stationary_get());
  public final static XsGnssPlatform XGP_Pedestrian = new XsGnssPlatform("XGP_Pedestrian", minimalJNI.XGP_Pedestrian_get());
  public final static XsGnssPlatform XGP_Automotive = new XsGnssPlatform("XGP_Automotive", minimalJNI.XGP_Automotive_get());
  public final static XsGnssPlatform XGP_AtSea = new XsGnssPlatform("XGP_AtSea", minimalJNI.XGP_AtSea_get());
  public final static XsGnssPlatform XGP_Airborne1g = new XsGnssPlatform("XGP_Airborne1g", minimalJNI.XGP_Airborne1g_get());
  public final static XsGnssPlatform XGP_Airborne2g = new XsGnssPlatform("XGP_Airborne2g", minimalJNI.XGP_Airborne2g_get());
  public final static XsGnssPlatform XGP_Airborne4g = new XsGnssPlatform("XGP_Airborne4g", minimalJNI.XGP_Airborne4g_get());
  public final static XsGnssPlatform XGP_Wrist = new XsGnssPlatform("XGP_Wrist", minimalJNI.XGP_Wrist_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsGnssPlatform swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsGnssPlatform.class + " with value " + swigValue);
  }

  private XsGnssPlatform(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsGnssPlatform(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsGnssPlatform(String swigName, XsGnssPlatform swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsGnssPlatform[] swigValues = { XGP_Portable, XGP_Stationary, XGP_Pedestrian, XGP_Automotive, XGP_AtSea, XGP_Airborne1g, XGP_Airborne2g, XGP_Airborne4g, XGP_Wrist };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

