/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsIccRepMotionResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsIccRepMotionResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsIccRepMotionResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsIccRepMotionResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_ddtAccuracy(float value) {
    minimalJNI.XsIccRepMotionResult_m_ddtAccuracy_set(swigCPtr, this, value);
  }

  public float getM_ddtAccuracy() {
    return minimalJNI.XsIccRepMotionResult_m_ddtAccuracy_get(swigCPtr, this);
  }

  public void setM_dimension(short value) {
    minimalJNI.XsIccRepMotionResult_m_dimension_set(swigCPtr, this, value);
  }

  public short getM_dimension() {
    return minimalJNI.XsIccRepMotionResult_m_dimension_get(swigCPtr, this);
  }

  public void setM_status(short value) {
    minimalJNI.XsIccRepMotionResult_m_status_set(swigCPtr, this, value);
  }

  public short getM_status() {
    return minimalJNI.XsIccRepMotionResult_m_status_get(swigCPtr, this);
  }

  public XsIccRepMotionResult() {
    this(minimalJNI.new_XsIccRepMotionResult__SWIG_0(), true);
  }

  public XsIccRepMotionResult(XsIccRepMotionResult other) {
    this(minimalJNI.new_XsIccRepMotionResult__SWIG_1(XsIccRepMotionResult.getCPtr(other), other), true);
  }

  public float ddtAccuracy() {
    return minimalJNI.XsIccRepMotionResult_ddtAccuracy(swigCPtr, this);
  }

  public short dimension() {
    return minimalJNI.XsIccRepMotionResult_dimension(swigCPtr, this);
  }

  public short status() {
    return minimalJNI.XsIccRepMotionResult_status(swigCPtr, this);
  }

}
