/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsMtDeviceConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsMtDeviceConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsMtDeviceConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsMtDeviceConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_deviceId(java.math.BigInteger value) {
    minimalJNI.XsMtDeviceConfiguration_m_deviceId_set(swigCPtr, this, value);
  }

  public java.math.BigInteger getM_deviceId() {
    return minimalJNI.XsMtDeviceConfiguration_m_deviceId_get(swigCPtr, this);
  }

  public void setM_reserved(SWIGTYPE_p_unsigned_char value) {
    minimalJNI.XsMtDeviceConfiguration_m_reserved_set(swigCPtr, this, SWIGTYPE_p_unsigned_char.getCPtr(value));
  }

  public SWIGTYPE_p_unsigned_char getM_reserved() {
    long cPtr = minimalJNI.XsMtDeviceConfiguration_m_reserved_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public void setM_filterProfile(int value) {
    minimalJNI.XsMtDeviceConfiguration_m_filterProfile_set(swigCPtr, this, value);
  }

  public int getM_filterProfile() {
    return minimalJNI.XsMtDeviceConfiguration_m_filterProfile_get(swigCPtr, this);
  }

  public void setM_fwRevMajor(short value) {
    minimalJNI.XsMtDeviceConfiguration_m_fwRevMajor_set(swigCPtr, this, value);
  }

  public short getM_fwRevMajor() {
    return minimalJNI.XsMtDeviceConfiguration_m_fwRevMajor_get(swigCPtr, this);
  }

  public void setM_fwRevMinor(short value) {
    minimalJNI.XsMtDeviceConfiguration_m_fwRevMinor_set(swigCPtr, this, value);
  }

  public short getM_fwRevMinor() {
    return minimalJNI.XsMtDeviceConfiguration_m_fwRevMinor_get(swigCPtr, this);
  }

  public void setM_fwRevRevision(short value) {
    minimalJNI.XsMtDeviceConfiguration_m_fwRevRevision_set(swigCPtr, this, value);
  }

  public short getM_fwRevRevision() {
    return minimalJNI.XsMtDeviceConfiguration_m_fwRevRevision_get(swigCPtr, this);
  }

  public void setM_filterType(char value) {
    minimalJNI.XsMtDeviceConfiguration_m_filterType_set(swigCPtr, this, value);
  }

  public char getM_filterType() {
    return minimalJNI.XsMtDeviceConfiguration_m_filterType_get(swigCPtr, this);
  }

  public void setM_filterMajor(short value) {
    minimalJNI.XsMtDeviceConfiguration_m_filterMajor_set(swigCPtr, this, value);
  }

  public short getM_filterMajor() {
    return minimalJNI.XsMtDeviceConfiguration_m_filterMajor_get(swigCPtr, this);
  }

  public void setM_filterMinor(short value) {
    minimalJNI.XsMtDeviceConfiguration_m_filterMinor_set(swigCPtr, this, value);
  }

  public short getM_filterMinor() {
    return minimalJNI.XsMtDeviceConfiguration_m_filterMinor_get(swigCPtr, this);
  }

  public XsMtDeviceConfiguration() {
    this(minimalJNI.new_XsMtDeviceConfiguration(), true);
  }

}
