/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsOperationalMode {
  public final static XsOperationalMode XOP_Unknown = new XsOperationalMode("XOP_Unknown");
  public final static XsOperationalMode XOP_LiveStream = new XsOperationalMode("XOP_LiveStream");
  public final static XsOperationalMode XOP_Obr = new XsOperationalMode("XOP_Obr");
  public final static XsOperationalMode XOP_Robr = new XsOperationalMode("XOP_Robr");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsOperationalMode swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsOperationalMode.class + " with value " + swigValue);
  }

  private XsOperationalMode(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsOperationalMode(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsOperationalMode(String swigName, XsOperationalMode swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsOperationalMode[] swigValues = { XOP_Unknown, XOP_LiveStream, XOP_Obr, XOP_Robr };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

