/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsOutputConfigurationArray {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsOutputConfigurationArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsOutputConfigurationArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsOutputConfigurationArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsOutputConfigurationArray(SWIGTYPE_p_XsSize count, XsOutputConfiguration src) {
    this(minimalJNI.new_XsOutputConfigurationArray__SWIG_0(SWIGTYPE_p_XsSize.getCPtr(count), XsOutputConfiguration.getCPtr(src), src), true);
  }

  public XsOutputConfigurationArray(SWIGTYPE_p_XsSize count) {
    this(minimalJNI.new_XsOutputConfigurationArray__SWIG_1(SWIGTYPE_p_XsSize.getCPtr(count)), true);
  }

  public XsOutputConfigurationArray() {
    this(minimalJNI.new_XsOutputConfigurationArray__SWIG_2(), true);
  }

  public XsOutputConfigurationArray(XsOutputConfigurationArray other) {
    this(minimalJNI.new_XsOutputConfigurationArray__SWIG_3(XsOutputConfigurationArray.getCPtr(other), other), true);
  }

  public XsOutputConfigurationArray(XsOutputConfiguration ref, SWIGTYPE_p_XsSize sz, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsOutputConfigurationArray__SWIG_4(XsOutputConfiguration.getCPtr(ref), ref, SWIGTYPE_p_XsSize.getCPtr(sz), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

  public void clear() {
    minimalJNI.XsOutputConfigurationArray_clear(swigCPtr, this);
  }

  public boolean opEquals(XsOutputConfigurationArray other) {
    return minimalJNI.XsOutputConfigurationArray_opEquals(swigCPtr, this, XsOutputConfigurationArray.getCPtr(other), other);
  }

  public boolean opUnequals(XsOutputConfigurationArray other) {
    return minimalJNI.XsOutputConfigurationArray_opUnequals(swigCPtr, this, XsOutputConfigurationArray.getCPtr(other), other);
  }

  public void reserve(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_reserve(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public SWIGTYPE_p_XsSize reserved() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsOutputConfigurationArray_reserved(swigCPtr, this), true);
  }

  public XsArrayDescriptor descriptor() {
    return new XsArrayDescriptor(minimalJNI.XsOutputConfigurationArray_descriptor(swigCPtr, this), false);
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t begin() {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t(minimalJNI.XsOutputConfigurationArray_begin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t end() {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t(minimalJNI.XsOutputConfigurationArray_end(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t rbegin() {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t(minimalJNI.XsOutputConfigurationArray_rbegin(swigCPtr, this), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t rend() {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t(minimalJNI.XsOutputConfigurationArray_rend(swigCPtr, this), true);
  }

  public XsOutputConfiguration opSquareBracket(int index) {
    return new XsOutputConfiguration(minimalJNI.XsOutputConfigurationArray_opSquareBracket(swigCPtr, this, index), false);
  }

  public XsOutputConfiguration value(SWIGTYPE_p_XsSize index) {
    return new XsOutputConfiguration(minimalJNI.XsOutputConfigurationArray_value(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index)), true);
  }

  public XsOutputConfiguration first() {
    return new XsOutputConfiguration(minimalJNI.XsOutputConfigurationArray_first(swigCPtr, this), true);
  }

  public XsOutputConfiguration last() {
    return new XsOutputConfiguration(minimalJNI.XsOutputConfigurationArray_last(swigCPtr, this), true);
  }

  public XsOutputConfiguration at(SWIGTYPE_p_XsSize index) {
    return new XsOutputConfiguration(minimalJNI.XsOutputConfigurationArray_at(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index)), false);
  }

  public void insert(XsOutputConfiguration item, SWIGTYPE_p_XsSize index) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_0(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item, SWIGTYPE_p_XsSize.getCPtr(index));
  }

  public void insert(XsOutputConfiguration items, SWIGTYPE_p_XsSize index, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_1(swigCPtr, this, XsOutputConfiguration.getCPtr(items), items, SWIGTYPE_p_XsSize.getCPtr(index), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void insert(XsOutputConfiguration item, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t it) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_2(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t.getCPtr(it));
  }

  public void insert(XsOutputConfiguration item, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t it) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_3(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t.getCPtr(it));
  }

  public void insert(XsOutputConfiguration items, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t it, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_4(swigCPtr, this, XsOutputConfiguration.getCPtr(items), items, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT_1_t.getCPtr(it), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void insert(XsOutputConfiguration items, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t it, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_insert__SWIG_5(swigCPtr, this, XsOutputConfiguration.getCPtr(items), items, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplConstT__1_t.getCPtr(it), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void push_back(XsOutputConfiguration item) {
    minimalJNI.XsOutputConfigurationArray_push_back(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item);
  }

  public void pop_back(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_pop_back__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void pop_back() {
    minimalJNI.XsOutputConfigurationArray_pop_back__SWIG_1(swigCPtr, this);
  }

  public void push_front(XsOutputConfiguration item) {
    minimalJNI.XsOutputConfigurationArray_push_front(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item);
  }

  public void pop_front(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_pop_front__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void pop_front() {
    minimalJNI.XsOutputConfigurationArray_pop_front__SWIG_1(swigCPtr, this);
  }

  public SWIGTYPE_p_XsSize size() {
    return new SWIGTYPE_p_XsSize(minimalJNI.XsOutputConfigurationArray_size(swigCPtr, this), true);
  }

  public void erase(SWIGTYPE_p_XsSize index, SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_erase__SWIG_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index), SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void erase(SWIGTYPE_p_XsSize index) {
    minimalJNI.XsOutputConfigurationArray_erase__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(index));
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT_1_t erase(SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT_1_t it) {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT_1_t(minimalJNI.XsOutputConfigurationArray_erase__SWIG_2(swigCPtr, this, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT_1_t.getCPtr(it)), true);
  }

  public SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT__1_t erase(SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT__1_t it) {
    return new SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT__1_t(minimalJNI.XsOutputConfigurationArray_erase__SWIG_3(swigCPtr, this, SWIGTYPE_p_XsArrayImplT_XsOutputConfiguration_g_xsOutputConfigurationArrayDescriptor_XsOutputConfigurationArray_t__IteratorImplT__1_t.getCPtr(it)), true);
  }

  public void assign(SWIGTYPE_p_XsSize count, XsOutputConfiguration src) {
    minimalJNI.XsOutputConfigurationArray_assign(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count), XsOutputConfiguration.getCPtr(src), src);
  }

  public void resize(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_resize(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void setSize(SWIGTYPE_p_XsSize count) {
    minimalJNI.XsOutputConfigurationArray_setSize(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(count));
  }

  public void append(XsOutputConfigurationArray other) {
    minimalJNI.XsOutputConfigurationArray_append(swigCPtr, this, XsOutputConfigurationArray.getCPtr(other), other);
  }

  public XsOutputConfigurationArray opSet(XsOutputConfigurationArray other) {
    return new XsOutputConfigurationArray(minimalJNI.XsOutputConfigurationArray_opSet(swigCPtr, this, XsOutputConfigurationArray.getCPtr(other), other), false);
  }

  public boolean empty() {
    return minimalJNI.XsOutputConfigurationArray_empty(swigCPtr, this);
  }

  public SWIGTYPE_p_XsOutputConfigurationArray inherited() {
    return new SWIGTYPE_p_XsOutputConfigurationArray(minimalJNI.XsOutputConfigurationArray_inherited(swigCPtr, this), false);
  }

  public void swap(XsOutputConfigurationArray other) {
    minimalJNI.XsOutputConfigurationArray_swap__SWIG_0(swigCPtr, this, XsOutputConfigurationArray.getCPtr(other), other);
  }

  public void swap(SWIGTYPE_p_XsSize a, SWIGTYPE_p_XsSize b) {
    minimalJNI.XsOutputConfigurationArray_swap__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(a), SWIGTYPE_p_XsSize.getCPtr(b));
  }

  public SWIGTYPE_p_XsOutputConfigurationArray opLeftShift(XsOutputConfiguration item) {
    return new SWIGTYPE_p_XsOutputConfigurationArray(minimalJNI.XsOutputConfigurationArray_opLeftShift(swigCPtr, this, XsOutputConfiguration.getCPtr(item), item), false);
  }

  public SWIGTYPE_p_ptrdiff_t find(XsOutputConfiguration needle) {
    return new SWIGTYPE_p_ptrdiff_t(minimalJNI.XsOutputConfigurationArray_find(swigCPtr, this, XsOutputConfiguration.getCPtr(needle), needle), true);
  }

  public void removeDuplicates() {
    minimalJNI.XsOutputConfigurationArray_removeDuplicates(swigCPtr, this);
  }

  public void removeDuplicatesPredicate(SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int predicate) {
    minimalJNI.XsOutputConfigurationArray_removeDuplicatesPredicate(swigCPtr, this, SWIGTYPE_p_f_p_q_const__void_p_q_const__void__int.getCPtr(predicate));
  }

  public void sort() {
    minimalJNI.XsOutputConfigurationArray_sort(swigCPtr, this);
  }

  public void reverse() {
    minimalJNI.XsOutputConfigurationArray_reverse(swigCPtr, this);
  }

}
