/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsOutputConfiguration {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsOutputConfiguration(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsOutputConfiguration obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsOutputConfiguration(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_dataIdentifier(SWIGTYPE_p_XsDataIdentifier value) {
    minimalJNI.XsOutputConfiguration_m_dataIdentifier_set(swigCPtr, this, SWIGTYPE_p_XsDataIdentifier.getCPtr(value));
  }

  public SWIGTYPE_p_XsDataIdentifier getM_dataIdentifier() {
    return new SWIGTYPE_p_XsDataIdentifier(minimalJNI.XsOutputConfiguration_m_dataIdentifier_get(swigCPtr, this), true);
  }

  public void setM_frequency(int value) {
    minimalJNI.XsOutputConfiguration_m_frequency_set(swigCPtr, this, value);
  }

  public int getM_frequency() {
    return minimalJNI.XsOutputConfiguration_m_frequency_get(swigCPtr, this);
  }

  public XsOutputConfiguration() {
    this(minimalJNI.new_XsOutputConfiguration__SWIG_0(), true);
  }

  public XsOutputConfiguration(SWIGTYPE_p_XsDataIdentifier di, int freq) {
    this(minimalJNI.new_XsOutputConfiguration__SWIG_1(SWIGTYPE_p_XsDataIdentifier.getCPtr(di), freq), true);
  }

  public boolean opEquals(XsOutputConfiguration other) {
    return minimalJNI.XsOutputConfiguration_opEquals(swigCPtr, this, XsOutputConfiguration.getCPtr(other), other);
  }

}
