/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsPortLinesOptions {
  public final static XsPortLinesOptions XPLO_Invalid = new XsPortLinesOptions("XPLO_Invalid", minimalJNI.XPLO_Invalid_get());
  public final static XsPortLinesOptions XPLO_RTS_Set = new XsPortLinesOptions("XPLO_RTS_Set", minimalJNI.XPLO_RTS_Set_get());
  public final static XsPortLinesOptions XPLO_RTS_Clear = new XsPortLinesOptions("XPLO_RTS_Clear", minimalJNI.XPLO_RTS_Clear_get());
  public final static XsPortLinesOptions XPLO_RTS_Ignore = new XsPortLinesOptions("XPLO_RTS_Ignore", minimalJNI.XPLO_RTS_Ignore_get());
  public final static XsPortLinesOptions XPLO_DTR_Set = new XsPortLinesOptions("XPLO_DTR_Set", minimalJNI.XPLO_DTR_Set_get());
  public final static XsPortLinesOptions XPLO_DTR_Clear = new XsPortLinesOptions("XPLO_DTR_Clear", minimalJNI.XPLO_DTR_Clear_get());
  public final static XsPortLinesOptions XPLO_DTR_Ignore = new XsPortLinesOptions("XPLO_DTR_Ignore", minimalJNI.XPLO_DTR_Ignore_get());
  public final static XsPortLinesOptions XPLO_All_Set = new XsPortLinesOptions("XPLO_All_Set", minimalJNI.XPLO_All_Set_get());
  public final static XsPortLinesOptions XPLO_All_Clear = new XsPortLinesOptions("XPLO_All_Clear", minimalJNI.XPLO_All_Clear_get());
  public final static XsPortLinesOptions XPLO_All_Ignore = new XsPortLinesOptions("XPLO_All_Ignore", minimalJNI.XPLO_All_Ignore_get());
  public final static XsPortLinesOptions XPLO_RtsCtsFlowControl = new XsPortLinesOptions("XPLO_RtsCtsFlowControl", minimalJNI.XPLO_RtsCtsFlowControl_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsPortLinesOptions swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsPortLinesOptions.class + " with value " + swigValue);
  }

  private XsPortLinesOptions(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsPortLinesOptions(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsPortLinesOptions(String swigName, XsPortLinesOptions swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsPortLinesOptions[] swigValues = { XPLO_Invalid, XPLO_RTS_Set, XPLO_RTS_Clear, XPLO_RTS_Ignore, XPLO_DTR_Set, XPLO_DTR_Clear, XPLO_DTR_Ignore, XPLO_All_Set, XPLO_All_Clear, XPLO_All_Ignore, XPLO_RtsCtsFlowControl };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

