/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsPortInfoArrayClass extends XsPortInfoArray {
  private transient long swigCPtr;

  protected XsPortInfoArrayClass(long cPtr, boolean cMemoryOwn) {
    super(minimalJNI.XsPortInfoArrayClass_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsPortInfoArrayClass obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsPortInfoArrayClass(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XsPortInfoArrayClass(SWIGTYPE_p_XsSize sz, XsPortInfoClass src) {
    this(minimalJNI.new_XsPortInfoArrayClass__SWIG_0(SWIGTYPE_p_XsSize.getCPtr(sz), XsPortInfoClass.getCPtr(src), src), true);
  }

  public XsPortInfoArrayClass(SWIGTYPE_p_XsSize sz) {
    this(minimalJNI.new_XsPortInfoArrayClass__SWIG_1(SWIGTYPE_p_XsSize.getCPtr(sz)), true);
  }

  public XsPortInfoArrayClass() {
    this(minimalJNI.new_XsPortInfoArrayClass__SWIG_2(), true);
  }

  public XsPortInfoArrayClass(XsPortInfoArrayClass other) {
    this(minimalJNI.new_XsPortInfoArrayClass__SWIG_3(XsPortInfoArrayClass.getCPtr(other), other), true);
  }

  public XsPortInfoArrayClass(XsPortInfoClass ref, SWIGTYPE_p_XsSize sz, SWIGTYPE_p_XsDataFlags flags) {
    this(minimalJNI.new_XsPortInfoArrayClass__SWIG_4(XsPortInfoClass.getCPtr(ref), ref, SWIGTYPE_p_XsSize.getCPtr(sz), SWIGTYPE_p_XsDataFlags.getCPtr(flags)), true);
  }

}
