/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsPvtDataUtcFlags {
  public final static XsPvtDataUtcFlags XPDUF_ValidDate = new XsPvtDataUtcFlags("XPDUF_ValidDate", minimalJNI.XPDUF_ValidDate_get());
  public final static XsPvtDataUtcFlags XPDUF_ValidTime = new XsPvtDataUtcFlags("XPDUF_ValidTime", minimalJNI.XPDUF_ValidTime_get());
  public final static XsPvtDataUtcFlags XPDUF_FullyResolved = new XsPvtDataUtcFlags("XPDUF_FullyResolved", minimalJNI.XPDUF_FullyResolved_get());
  public final static XsPvtDataUtcFlags XPDUF_ValidMag = new XsPvtDataUtcFlags("XPDUF_ValidMag", minimalJNI.XPDUF_ValidMag_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsPvtDataUtcFlags swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsPvtDataUtcFlags.class + " with value " + swigValue);
  }

  private XsPvtDataUtcFlags(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsPvtDataUtcFlags(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsPvtDataUtcFlags(String swigName, XsPvtDataUtcFlags swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsPvtDataUtcFlags[] swigValues = { XPDUF_ValidDate, XPDUF_ValidTime, XPDUF_FullyResolved, XPDUF_ValidMag };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

