/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsPvtDataQualityIndicator {
  public final static XsPvtDataQualityIndicator XPDQI_NoFix = new XsPvtDataQualityIndicator("XPDQI_NoFix", minimalJNI.XPDQI_NoFix_get());
  public final static XsPvtDataQualityIndicator XPDQI_DeadReckiningOnly = new XsPvtDataQualityIndicator("XPDQI_DeadReckiningOnly", minimalJNI.XPDQI_DeadReckiningOnly_get());
  public final static XsPvtDataQualityIndicator XPDQI_2DFix = new XsPvtDataQualityIndicator("XPDQI_2DFix", minimalJNI.XPDQI_2DFix_get());
  public final static XsPvtDataQualityIndicator XPDQI_3DFix = new XsPvtDataQualityIndicator("XPDQI_3DFix", minimalJNI.XPDQI_3DFix_get());
  public final static XsPvtDataQualityIndicator XPDQI_GnssAndDeadReck = new XsPvtDataQualityIndicator("XPDQI_GnssAndDeadReck", minimalJNI.XPDQI_GnssAndDeadReck_get());
  public final static XsPvtDataQualityIndicator XPDQI_TimeOnlyFix = new XsPvtDataQualityIndicator("XPDQI_TimeOnlyFix", minimalJNI.XPDQI_TimeOnlyFix_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsPvtDataQualityIndicator swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsPvtDataQualityIndicator.class + " with value " + swigValue);
  }

  private XsPvtDataQualityIndicator(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsPvtDataQualityIndicator(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsPvtDataQualityIndicator(String swigName, XsPvtDataQualityIndicator swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsPvtDataQualityIndicator[] swigValues = { XPDQI_NoFix, XPDQI_DeadReckiningOnly, XPDQI_2DFix, XPDQI_3DFix, XPDQI_GnssAndDeadReck, XPDQI_TimeOnlyFix };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

