/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsRawGnssPvtData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsRawGnssPvtData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsRawGnssPvtData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsRawGnssPvtData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setM_itow(long value) {
    minimalJNI.XsRawGnssPvtData_m_itow_set(swigCPtr, this, value);
  }

  public long getM_itow() {
    return minimalJNI.XsRawGnssPvtData_m_itow_get(swigCPtr, this);
  }

  public void setM_year(int value) {
    minimalJNI.XsRawGnssPvtData_m_year_set(swigCPtr, this, value);
  }

  public int getM_year() {
    return minimalJNI.XsRawGnssPvtData_m_year_get(swigCPtr, this);
  }

  public void setM_month(short value) {
    minimalJNI.XsRawGnssPvtData_m_month_set(swigCPtr, this, value);
  }

  public short getM_month() {
    return minimalJNI.XsRawGnssPvtData_m_month_get(swigCPtr, this);
  }

  public void setM_day(short value) {
    minimalJNI.XsRawGnssPvtData_m_day_set(swigCPtr, this, value);
  }

  public short getM_day() {
    return minimalJNI.XsRawGnssPvtData_m_day_get(swigCPtr, this);
  }

  public void setM_hour(short value) {
    minimalJNI.XsRawGnssPvtData_m_hour_set(swigCPtr, this, value);
  }

  public short getM_hour() {
    return minimalJNI.XsRawGnssPvtData_m_hour_get(swigCPtr, this);
  }

  public void setM_min(short value) {
    minimalJNI.XsRawGnssPvtData_m_min_set(swigCPtr, this, value);
  }

  public short getM_min() {
    return minimalJNI.XsRawGnssPvtData_m_min_get(swigCPtr, this);
  }

  public void setM_sec(short value) {
    minimalJNI.XsRawGnssPvtData_m_sec_set(swigCPtr, this, value);
  }

  public short getM_sec() {
    return minimalJNI.XsRawGnssPvtData_m_sec_get(swigCPtr, this);
  }

  public void setM_valid(short value) {
    minimalJNI.XsRawGnssPvtData_m_valid_set(swigCPtr, this, value);
  }

  public short getM_valid() {
    return minimalJNI.XsRawGnssPvtData_m_valid_get(swigCPtr, this);
  }

  public void setM_tAcc(long value) {
    minimalJNI.XsRawGnssPvtData_m_tAcc_set(swigCPtr, this, value);
  }

  public long getM_tAcc() {
    return minimalJNI.XsRawGnssPvtData_m_tAcc_get(swigCPtr, this);
  }

  public void setM_nano(int value) {
    minimalJNI.XsRawGnssPvtData_m_nano_set(swigCPtr, this, value);
  }

  public int getM_nano() {
    return minimalJNI.XsRawGnssPvtData_m_nano_get(swigCPtr, this);
  }

  public void setM_fixType(short value) {
    minimalJNI.XsRawGnssPvtData_m_fixType_set(swigCPtr, this, value);
  }

  public short getM_fixType() {
    return minimalJNI.XsRawGnssPvtData_m_fixType_get(swigCPtr, this);
  }

  public void setM_flags(short value) {
    minimalJNI.XsRawGnssPvtData_m_flags_set(swigCPtr, this, value);
  }

  public short getM_flags() {
    return minimalJNI.XsRawGnssPvtData_m_flags_get(swigCPtr, this);
  }

  public void setM_numSv(short value) {
    minimalJNI.XsRawGnssPvtData_m_numSv_set(swigCPtr, this, value);
  }

  public short getM_numSv() {
    return minimalJNI.XsRawGnssPvtData_m_numSv_get(swigCPtr, this);
  }

  public void setM_res1(short value) {
    minimalJNI.XsRawGnssPvtData_m_res1_set(swigCPtr, this, value);
  }

  public short getM_res1() {
    return minimalJNI.XsRawGnssPvtData_m_res1_get(swigCPtr, this);
  }

  public void setM_lon(int value) {
    minimalJNI.XsRawGnssPvtData_m_lon_set(swigCPtr, this, value);
  }

  public int getM_lon() {
    return minimalJNI.XsRawGnssPvtData_m_lon_get(swigCPtr, this);
  }

  public void setM_lat(int value) {
    minimalJNI.XsRawGnssPvtData_m_lat_set(swigCPtr, this, value);
  }

  public int getM_lat() {
    return minimalJNI.XsRawGnssPvtData_m_lat_get(swigCPtr, this);
  }

  public void setM_height(int value) {
    minimalJNI.XsRawGnssPvtData_m_height_set(swigCPtr, this, value);
  }

  public int getM_height() {
    return minimalJNI.XsRawGnssPvtData_m_height_get(swigCPtr, this);
  }

  public void setM_hMsl(int value) {
    minimalJNI.XsRawGnssPvtData_m_hMsl_set(swigCPtr, this, value);
  }

  public int getM_hMsl() {
    return minimalJNI.XsRawGnssPvtData_m_hMsl_get(swigCPtr, this);
  }

  public void setM_hAcc(long value) {
    minimalJNI.XsRawGnssPvtData_m_hAcc_set(swigCPtr, this, value);
  }

  public long getM_hAcc() {
    return minimalJNI.XsRawGnssPvtData_m_hAcc_get(swigCPtr, this);
  }

  public void setM_vAcc(long value) {
    minimalJNI.XsRawGnssPvtData_m_vAcc_set(swigCPtr, this, value);
  }

  public long getM_vAcc() {
    return minimalJNI.XsRawGnssPvtData_m_vAcc_get(swigCPtr, this);
  }

  public void setM_velN(int value) {
    minimalJNI.XsRawGnssPvtData_m_velN_set(swigCPtr, this, value);
  }

  public int getM_velN() {
    return minimalJNI.XsRawGnssPvtData_m_velN_get(swigCPtr, this);
  }

  public void setM_velE(int value) {
    minimalJNI.XsRawGnssPvtData_m_velE_set(swigCPtr, this, value);
  }

  public int getM_velE() {
    return minimalJNI.XsRawGnssPvtData_m_velE_get(swigCPtr, this);
  }

  public void setM_velD(int value) {
    minimalJNI.XsRawGnssPvtData_m_velD_set(swigCPtr, this, value);
  }

  public int getM_velD() {
    return minimalJNI.XsRawGnssPvtData_m_velD_get(swigCPtr, this);
  }

  public void setM_gSpeed(int value) {
    minimalJNI.XsRawGnssPvtData_m_gSpeed_set(swigCPtr, this, value);
  }

  public int getM_gSpeed() {
    return minimalJNI.XsRawGnssPvtData_m_gSpeed_get(swigCPtr, this);
  }

  public void setM_headMot(int value) {
    minimalJNI.XsRawGnssPvtData_m_headMot_set(swigCPtr, this, value);
  }

  public int getM_headMot() {
    return minimalJNI.XsRawGnssPvtData_m_headMot_get(swigCPtr, this);
  }

  public void setM_sAcc(long value) {
    minimalJNI.XsRawGnssPvtData_m_sAcc_set(swigCPtr, this, value);
  }

  public long getM_sAcc() {
    return minimalJNI.XsRawGnssPvtData_m_sAcc_get(swigCPtr, this);
  }

  public void setM_headAcc(long value) {
    minimalJNI.XsRawGnssPvtData_m_headAcc_set(swigCPtr, this, value);
  }

  public long getM_headAcc() {
    return minimalJNI.XsRawGnssPvtData_m_headAcc_get(swigCPtr, this);
  }

  public void setM_headVeh(int value) {
    minimalJNI.XsRawGnssPvtData_m_headVeh_set(swigCPtr, this, value);
  }

  public int getM_headVeh() {
    return minimalJNI.XsRawGnssPvtData_m_headVeh_get(swigCPtr, this);
  }

  public void setM_gdop(int value) {
    minimalJNI.XsRawGnssPvtData_m_gdop_set(swigCPtr, this, value);
  }

  public int getM_gdop() {
    return minimalJNI.XsRawGnssPvtData_m_gdop_get(swigCPtr, this);
  }

  public void setM_pdop(int value) {
    minimalJNI.XsRawGnssPvtData_m_pdop_set(swigCPtr, this, value);
  }

  public int getM_pdop() {
    return minimalJNI.XsRawGnssPvtData_m_pdop_get(swigCPtr, this);
  }

  public void setM_tdop(int value) {
    minimalJNI.XsRawGnssPvtData_m_tdop_set(swigCPtr, this, value);
  }

  public int getM_tdop() {
    return minimalJNI.XsRawGnssPvtData_m_tdop_get(swigCPtr, this);
  }

  public void setM_vdop(int value) {
    minimalJNI.XsRawGnssPvtData_m_vdop_set(swigCPtr, this, value);
  }

  public int getM_vdop() {
    return minimalJNI.XsRawGnssPvtData_m_vdop_get(swigCPtr, this);
  }

  public void setM_hdop(int value) {
    minimalJNI.XsRawGnssPvtData_m_hdop_set(swigCPtr, this, value);
  }

  public int getM_hdop() {
    return minimalJNI.XsRawGnssPvtData_m_hdop_get(swigCPtr, this);
  }

  public void setM_ndop(int value) {
    minimalJNI.XsRawGnssPvtData_m_ndop_set(swigCPtr, this, value);
  }

  public int getM_ndop() {
    return minimalJNI.XsRawGnssPvtData_m_ndop_get(swigCPtr, this);
  }

  public void setM_edop(int value) {
    minimalJNI.XsRawGnssPvtData_m_edop_set(swigCPtr, this, value);
  }

  public int getM_edop() {
    return minimalJNI.XsRawGnssPvtData_m_edop_get(swigCPtr, this);
  }

  public boolean opEquals(XsRawGnssPvtData other) {
    return minimalJNI.XsRawGnssPvtData_opEquals(swigCPtr, this, XsRawGnssPvtData.getCPtr(other), other);
  }

  public XsRawGnssPvtData() {
    this(minimalJNI.new_XsRawGnssPvtData(), true);
  }

}
