/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsRejectReason {
  public final static XsRejectReason XRR_Unknown = new XsRejectReason("XRR_Unknown", minimalJNI.XRR_Unknown_get());
  public final static XsRejectReason XRR_VersionMismatch = new XsRejectReason("XRR_VersionMismatch", minimalJNI.XRR_VersionMismatch_get());
  public final static XsRejectReason XRR_Blacklisted = new XsRejectReason("XRR_Blacklisted", minimalJNI.XRR_Blacklisted_get());
  public final static XsRejectReason XRR_StationIsDisconnecting = new XsRejectReason("XRR_StationIsDisconnecting", minimalJNI.XRR_StationIsDisconnecting_get());
  public final static XsRejectReason XRR_SystemIsOperational = new XsRejectReason("XRR_SystemIsOperational", minimalJNI.XRR_SystemIsOperational_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsRejectReason swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsRejectReason.class + " with value " + swigValue);
  }

  private XsRejectReason(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsRejectReason(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsRejectReason(String swigName, XsRejectReason swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsRejectReason[] swigValues = { XRR_Unknown, XRR_VersionMismatch, XRR_Blacklisted, XRR_StationIsDisconnecting, XRR_SystemIsOperational };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

