/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsScanner {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsScanner(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsScanner obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsScanner(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static XsPortInfoArrayClass scanPorts(XsBaudRate baudrate, int singleScanTimeout, boolean ignoreNonXsensDevices, boolean detectRs485) {
    return new XsPortInfoArrayClass(minimalJNI.XsScanner_scanPorts__SWIG_0(baudrate.swigValue(), singleScanTimeout, ignoreNonXsensDevices, detectRs485), true);
  }

  public static XsPortInfoArrayClass scanPorts(XsBaudRate baudrate, int singleScanTimeout, boolean ignoreNonXsensDevices) {
    return new XsPortInfoArrayClass(minimalJNI.XsScanner_scanPorts__SWIG_1(baudrate.swigValue(), singleScanTimeout, ignoreNonXsensDevices), true);
  }

  public static XsPortInfoArrayClass scanPorts(XsBaudRate baudrate, int singleScanTimeout) {
    return new XsPortInfoArrayClass(minimalJNI.XsScanner_scanPorts__SWIG_2(baudrate.swigValue(), singleScanTimeout), true);
  }

  public static XsPortInfoArrayClass scanPorts(XsBaudRate baudrate) {
    return new XsPortInfoArrayClass(minimalJNI.XsScanner_scanPorts__SWIG_3(baudrate.swigValue()), true);
  }

  public static XsPortInfoArrayClass scanPorts() {
    return new XsPortInfoArrayClass(minimalJNI.XsScanner_scanPorts__SWIG_4(), true);
  }

  public XsScanner() {
    this(minimalJNI.new_XsScanner(), true);
  }

}
