/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsSdiData {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected XsSdiData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsSdiData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsSdiData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public XsSdiData() {
    this(minimalJNI.new_XsSdiData__SWIG_0(), true);
  }

  public XsSdiData(XsQuaternionClass dq, XsVectorClass dv) {
    this(minimalJNI.new_XsSdiData__SWIG_1(XsQuaternionClass.getCPtr(dq), dq, XsVectorClass.getCPtr(dv), dv), true);
  }

  public XsSdiData(XsSdiData other) {
    this(minimalJNI.new_XsSdiData__SWIG_2(XsSdiData.getCPtr(other), other), true);
  }

  public XsSdiData opSet(XsSdiData other) {
    return new XsSdiData(minimalJNI.XsSdiData_opSet(swigCPtr, this, XsSdiData.getCPtr(other), other), false);
  }

  public void zero() {
    minimalJNI.XsSdiData_zero(swigCPtr, this);
  }

  public XsQuaternionClass orientationIncrement() {
    return new XsQuaternionClass(minimalJNI.XsSdiData_orientationIncrement(swigCPtr, this), false);
  }

  public void setOrientationIncrement(XsQuaternionClass dq) {
    minimalJNI.XsSdiData_setOrientationIncrement(swigCPtr, this, XsQuaternionClass.getCPtr(dq), dq);
  }

  public XsVector3 velocityIncrement() {
    return new XsVector3(minimalJNI.XsSdiData_velocityIncrement(swigCPtr, this), false);
  }

  public void setVelocityIncrement(XsVectorClass dv) {
    minimalJNI.XsSdiData_setVelocityIncrement(swigCPtr, this, XsVectorClass.getCPtr(dv), dv);
  }

  public boolean opEquals(XsSdiData other) {
    return minimalJNI.XsSdiData_opEquals(swigCPtr, this, XsSdiData.getCPtr(other), other);
  }

}
