/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public final class XsSelfTestFlag {
  public final static XsSelfTestFlag XSTF_X = new XsSelfTestFlag("XSTF_X", minimalJNI.XSTF_X_get());
  public final static XsSelfTestFlag XSTF_Y = new XsSelfTestFlag("XSTF_Y", minimalJNI.XSTF_Y_get());
  public final static XsSelfTestFlag XSTF_Z = new XsSelfTestFlag("XSTF_Z", minimalJNI.XSTF_Z_get());
  public final static XsSelfTestFlag XSTF_AccShift = new XsSelfTestFlag("XSTF_AccShift", minimalJNI.XSTF_AccShift_get());
  public final static XsSelfTestFlag XSTF_AccX = new XsSelfTestFlag("XSTF_AccX", minimalJNI.XSTF_AccX_get());
  public final static XsSelfTestFlag XSTF_AccY = new XsSelfTestFlag("XSTF_AccY", minimalJNI.XSTF_AccY_get());
  public final static XsSelfTestFlag XSTF_AccZ = new XsSelfTestFlag("XSTF_AccZ", minimalJNI.XSTF_AccZ_get());
  public final static XsSelfTestFlag XSTF_GyrShift = new XsSelfTestFlag("XSTF_GyrShift", minimalJNI.XSTF_GyrShift_get());
  public final static XsSelfTestFlag XSTF_GyrX = new XsSelfTestFlag("XSTF_GyrX", minimalJNI.XSTF_GyrX_get());
  public final static XsSelfTestFlag XSTF_GyrY = new XsSelfTestFlag("XSTF_GyrY", minimalJNI.XSTF_GyrY_get());
  public final static XsSelfTestFlag XSTF_GyrZ = new XsSelfTestFlag("XSTF_GyrZ", minimalJNI.XSTF_GyrZ_get());
  public final static XsSelfTestFlag XSTF_MagShift = new XsSelfTestFlag("XSTF_MagShift", minimalJNI.XSTF_MagShift_get());
  public final static XsSelfTestFlag XSTF_MagX = new XsSelfTestFlag("XSTF_MagX", minimalJNI.XSTF_MagX_get());
  public final static XsSelfTestFlag XSTF_MagY = new XsSelfTestFlag("XSTF_MagY", minimalJNI.XSTF_MagY_get());
  public final static XsSelfTestFlag XSTF_MagZ = new XsSelfTestFlag("XSTF_MagZ", minimalJNI.XSTF_MagZ_get());
  public final static XsSelfTestFlag XSTF_Baro = new XsSelfTestFlag("XSTF_Baro", minimalJNI.XSTF_Baro_get());
  public final static XsSelfTestFlag XSTF_Gnss = new XsSelfTestFlag("XSTF_Gnss", minimalJNI.XSTF_Gnss_get());
  public final static XsSelfTestFlag XSTF_Battery = new XsSelfTestFlag("XSTF_Battery", minimalJNI.XSTF_Battery_get());
  public final static XsSelfTestFlag XSTF_Flash = new XsSelfTestFlag("XSTF_Flash", minimalJNI.XSTF_Flash_get());
  public final static XsSelfTestFlag XSTF_Button = new XsSelfTestFlag("XSTF_Button", minimalJNI.XSTF_Button_get());
  public final static XsSelfTestFlag XSTF_Sync = new XsSelfTestFlag("XSTF_Sync", minimalJNI.XSTF_Sync_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static XsSelfTestFlag swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + XsSelfTestFlag.class + " with value " + swigValue);
  }

  private XsSelfTestFlag(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private XsSelfTestFlag(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private XsSelfTestFlag(String swigName, XsSelfTestFlag swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static XsSelfTestFlag[] swigValues = { XSTF_X, XSTF_Y, XSTF_Z, XSTF_AccShift, XSTF_AccX, XSTF_AccY, XSTF_AccZ, XSTF_GyrShift, XSTF_GyrX, XSTF_GyrY, XSTF_GyrZ, XSTF_MagShift, XSTF_MagX, XSTF_MagY, XSTF_MagZ, XSTF_Baro, XSTF_Gnss, XSTF_Battery, XSTF_Flash, XSTF_Button, XSTF_Sync };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

