/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package asdf;

public class XsVector3 extends XsVectorClass {
  private transient long swigCPtr;

  protected XsVector3(long cPtr, boolean cMemoryOwn) {
    super(minimalJNI.XsVector3_SWIGUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  protected static long getCPtr(XsVector3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        minimalJNI.delete_XsVector3(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public XsVector3() {
    this(minimalJNI.new_XsVector3__SWIG_0(), true);
  }

  public XsVector3(XsVector3 other) {
    this(minimalJNI.new_XsVector3__SWIG_1(XsVector3.getCPtr(other), other), true);
  }

  public XsVector3(XsVectorClass other) {
    this(minimalJNI.new_XsVector3__SWIG_2(XsVectorClass.getCPtr(other), other), true);
  }

  public XsVector3(SWIGTYPE_p_XsReal x, SWIGTYPE_p_XsReal y, SWIGTYPE_p_XsReal z) {
    this(minimalJNI.new_XsVector3__SWIG_3(SWIGTYPE_p_XsReal.getCPtr(x), SWIGTYPE_p_XsReal.getCPtr(y), SWIGTYPE_p_XsReal.getCPtr(z)), true);
  }

  public static XsVector3 zero3() {
    return new XsVector3(minimalJNI.XsVector3_zero3(), false);
  }

  public XsVectorClass opSet(XsVectorClass other) {
    return new XsVectorClass(minimalJNI.XsVector3_opSet__SWIG_0_0(swigCPtr, this, XsVectorClass.getCPtr(other), other), false);
  }

  public XsVector3 opSet(XsVector3 other) {
    return new XsVector3(minimalJNI.XsVector3_opSet__SWIG_1(swigCPtr, this, XsVector3.getCPtr(other), other), false);
  }

  public void assign(SWIGTYPE_p_XsSize sz, SWIGTYPE_p_XsReal src) {
    minimalJNI.XsVector3_assign__SWIG_0_0(swigCPtr, this, SWIGTYPE_p_XsSize.getCPtr(sz), SWIGTYPE_p_XsReal.getCPtr(src));
  }

  public void assign(SWIGTYPE_p_XsReal x, SWIGTYPE_p_XsReal y, SWIGTYPE_p_XsReal z) {
    minimalJNI.XsVector3_assign__SWIG_1(swigCPtr, this, SWIGTYPE_p_XsReal.getCPtr(x), SWIGTYPE_p_XsReal.getCPtr(y), SWIGTYPE_p_XsReal.getCPtr(z));
  }

}
